type Player = {
  lastName: string;
  jerseyNumber: number;
  teamPrimaryColor: string;
  teamSecondaryColor: string;
};

const players: Player[] = [
 //Buffalo Bills
 { lastName: "Coleman", jerseyNumber: 0, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Palmer", jerseyNumber: 5, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Shakir", jerseyNumber: 10, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Dawkins", jerseyNumber: 73, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Edwards", jerseyNumber: 76, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { lastName: "McGovern", jerseyNumber: 66, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Torrence", jerseyNumber: 64, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Brown", jerseyNumber: 79, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Kincaid", jerseyNumber: 86, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Allen", jerseyNumber: 17, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Cook", jerseyNumber: 4, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Gilliam", jerseyNumber: 41, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Rousseau", jerseyNumber: 50, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Jones", jerseyNumber: 92, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Oliver", jerseyNumber: 91, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Bosa", jerseyNumber: 97, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Milano", jerseyNumber: 58, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Bernard", jerseyNumber: 43, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Benford", jerseyNumber: 47, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Bishop", jerseyNumber: 32, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },

  //Dolphins
   { lastName: 'Waddle', jerseyNumber: 17, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Hill', jerseyNumber: 10, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Washington', jerseyNumber: 6, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Paul', jerseyNumber: 52, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Daniels', jerseyNumber: 78, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Brewer', jerseyNumber: 55, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Savaiinaea', jerseyNumber: 72, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Jackson', jerseyNumber: 73, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Waller', jerseyNumber: 83, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Tagovailoa', jerseyNumber: 1, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Achane', jerseyNumber: 28, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Ingold', jerseyNumber: 30, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Grant', jerseyNumber: 90, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Jones', jerseyNumber: 95, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Sieler', jerseyNumber: 92, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Phillips', jerseyNumber: 15, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Brooks', jerseyNumber: 20, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Dodson', jerseyNumber: 11, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Chubb', jerseyNumber: 2, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Duck', jerseyNumber: 36, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Melifonwu', jerseyNumber: 9, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Fitzpatrick', jerseyNumber: 29, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Jones', jerseyNumber: 23, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },
  { lastName: 'Hilton', jerseyNumber: 38, teamPrimaryColor: '#008e97', teamSecondaryColor: '#ffffff' },

  // New England Patriots (Primary: #002244, Secondary: #C60C30)
  { lastName: "Diggs", jerseyNumber: 8, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "Hollins", jerseyNumber: 13, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "Douglas", jerseyNumber: 3, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "Campbell", jerseyNumber: 66, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "Wilson", jerseyNumber: 58, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "Bradbury", jerseyNumber: 65, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "Onwenu", jerseyNumber: 71, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "Moses", jerseyNumber: 76, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "Henry", jerseyNumber: 85, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "Maye", jerseyNumber: 10, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "Stevenson", jerseyNumber: 38, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "White", jerseyNumber: 99, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "Barmore", jerseyNumber: 90, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "Williams", jerseyNumber: 97, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "Landry", jerseyNumber: 2, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "Elliss", jerseyNumber: 53, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "Spillane", jerseyNumber: 14, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "Jennings", jerseyNumber: 33, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "Davis", jerseyNumber: 7, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "Dugger", jerseyNumber: 23, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "Peppers", jerseyNumber: 5, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "Gonzalez", jerseyNumber: 0, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
  { lastName: "Jones", jerseyNumber: 25, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },

  //New York Jets
  { lastName: "Wilson", jerseyNumber: 5, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "Reynolds", jerseyNumber: 83, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "Johnson", jerseyNumber: 16, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "Fashanu", jerseyNumber: 74, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "Simpson", jerseyNumber: 76, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "Tippmann", jerseyNumber: 66, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "Vera-Tucker", jerseyNumber: 75, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "Membou", jerseyNumber: 70, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "Taylor", jerseyNumber: 85, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "Fields", jerseyNumber: 7, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "Hall", jerseyNumber: 20, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "Beck", jerseyNumber: 47, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "McDonald IV", jerseyNumber: 9, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "Cowart", jerseyNumber: 93, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "Williams", jerseyNumber: 95, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "Johnson", jerseyNumber: 11, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "Williams", jerseyNumber: 56, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "Sherwood", jerseyNumber: 44, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "Gardner", jerseyNumber: 1, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "Moore", jerseyNumber: 27, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "Cisco", jerseyNumber: 8, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "Stephens", jerseyNumber: 21, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
  { lastName: "Carter II", jerseyNumber: 30, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },

    //Dallas Cowboys
    { lastName: "Pickens", jerseyNumber: 3, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Tolbert", jerseyNumber: 1, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Lamb", jerseyNumber: 88, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Guyton", jerseyNumber: 60, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Smith", jerseyNumber: 73, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Beebe", jerseyNumber: 56, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Booker", jerseyNumber: 52, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Steele", jerseyNumber: 78, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Ferguson", jerseyNumber: 87, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Prescott", jerseyNumber: 4, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Williams", jerseyNumber: 33, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Luepke", jerseyNumber: 40, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Fowler", jerseyNumber: 13, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Smith", jerseyNumber: 58, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Odighizuwa", jerseyNumber: 97, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Parsons", jerseyNumber: 11, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Overshown", jerseyNumber: 0, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Murray", jerseyNumber: 59, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Diggs", jerseyNumber: 7, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Hooker", jerseyNumber: 28, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Wilson", jerseyNumber: 6, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Elam", jerseyNumber: 20, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Bland", jerseyNumber: 26, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },

//New York Giants
{ lastName: "Nabers", jerseyNumber: 1, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
  { lastName: "Slayton", jerseyNumber: 18, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
  { lastName: "Robinson", jerseyNumber: 17, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
  { lastName: "Thomas", jerseyNumber: 78, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
  { lastName: "Runyan", jerseyNumber: 76, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
  { lastName: "Schmitz Jr.", jerseyNumber: 61, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
  { lastName: "Van Roten", jerseyNumber: 74, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
  { lastName: "Eluemunor", jerseyNumber: 72, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
  { lastName: "Johnson", jerseyNumber: 84, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
  { lastName: "Wilson", jerseyNumber: 3, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
  { lastName: "Tracy Jr.", jerseyNumber: 29, teamPrimaryColor: "blue", teamSecondaryColor: "white" },

  { lastName: "Robertson-Harris", jerseyNumber: 95, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
  { lastName: "Lawrence II", jerseyNumber: 97, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
  { lastName: "Núñez-Roches", jerseyNumber: 93, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
  { lastName: "Burns", jerseyNumber: 0, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
  { lastName: "Okereke", jerseyNumber: 58, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
  { lastName: "McFadden", jerseyNumber: 41, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
  { lastName: "Carter", jerseyNumber: 51, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
  { lastName: "Adebo", jerseyNumber: 21, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
  { lastName: "Nubin", jerseyNumber: 27, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
  { lastName: "Holland", jerseyNumber: 8, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
  { lastName: "Banks", jerseyNumber: 2, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
  { lastName: "Phillips", jerseyNumber: 22, teamPrimaryColor: "blue", teamSecondaryColor: "white" },

//Philadelphia Eagles
{ lastName: "Brown", jerseyNumber: 11, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "Dotson", jerseyNumber: 2, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "Smith", jerseyNumber: 6, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "Mailata", jerseyNumber: 68, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "Dickerson", jerseyNumber: 69, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "Jurgens", jerseyNumber: 51, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "Steen", jerseyNumber: 56, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "Johnson", jerseyNumber: 65, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "Goedert", jerseyNumber: 88, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "Hurts", jerseyNumber: 1, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "Barkley", jerseyNumber: 26, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "VanSumeren", jerseyNumber: 43, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },

{ lastName: "Ojomo", jerseyNumber: 97, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "Davis", jerseyNumber: 90, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "Carter", jerseyNumber: 98, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "Smith Jr.", jerseyNumber: 3, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "Baun", jerseyNumber: 53, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "Dean", jerseyNumber: 17, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "Hunt", jerseyNumber: 58, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "Ringo", jerseyNumber: 7, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "Brown", jerseyNumber: 21, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "Blankenship", jerseyNumber: 32, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "Mitchell", jerseyNumber: 27, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ lastName: "DeJean", jerseyNumber: 33, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },

{ lastName: "McLaurin", jerseyNumber: 17, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ lastName: "Brown", jerseyNumber: 85, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ lastName: "Samuel", jerseyNumber: 1, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ lastName: "Tunsil", jerseyNumber: 78, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ lastName: "Coleman", jerseyNumber: 74, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ lastName: "Biadasz", jerseyNumber: 63, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ lastName: "Cosmi", jerseyNumber: 76, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ lastName: "Wylie", jerseyNumber: 71, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ lastName: "Ertz", jerseyNumber: 86, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ lastName: "Daniels", jerseyNumber: 5, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ lastName: "Robinson Jr.", jerseyNumber: 8, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },

{ lastName: "Armstrong", jerseyNumber: 92, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ lastName: "Payne", jerseyNumber: 94, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ lastName: "Kinlaw", jerseyNumber: 52, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ lastName: "Miller", jerseyNumber: 24, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ lastName: "Luvu", jerseyNumber: 4, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ lastName: "Wagner", jerseyNumber: 54, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ lastName: "Amos", jerseyNumber: 23, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ lastName: "Harris", jerseyNumber: 3, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ lastName: "Martin", jerseyNumber: 20, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ lastName: "Lattimore", jerseyNumber: 2, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ lastName: "Sainristil", jerseyNumber: 0, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },

//Ravens
{ lastName: "Hopkins", jerseyNumber: 10, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Bateman", jerseyNumber: 7, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Flowers", jerseyNumber: 4, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Stanley", jerseyNumber: 79, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Voorhees", jerseyNumber: 72, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Linderbaum", jerseyNumber: 64, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Faalele", jerseyNumber: 77, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Rosengarten", jerseyNumber: 70, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Andrews", jerseyNumber: 89, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Jackson", jerseyNumber: 8, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Henry", jerseyNumber: 22, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Ricard", jerseyNumber: 42, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Washington", jerseyNumber: 96, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Jones", jerseyNumber: 98, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Madubuike", jerseyNumber: 92, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Oweh", jerseyNumber: 99, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Simpson", jerseyNumber: 32, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Smith", jerseyNumber: 0, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Van Noy", jerseyNumber: 53, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Wiggins", jerseyNumber: 2, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Hamilton", jerseyNumber: 14, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Starks", jerseyNumber: 24, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Alexander", jerseyNumber: 23, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
  { lastName: "Humphrey", jerseyNumber: 44, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },

  // Bengals
  { lastName: "Chase", jerseyNumber: 1, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
  { lastName: "Higgins", jerseyNumber: 5, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
  { lastName: "Iosivas", jerseyNumber: 80, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
  { lastName: "Brown Jr.", jerseyNumber: 75, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
  { lastName: "Fairchild", jerseyNumber: 63, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
  { lastName: "Karras", jerseyNumber: 64, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
  { lastName: "Patrick", jerseyNumber: 62, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
  { lastName: "Mims", jerseyNumber: 71, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
  { lastName: "Gesicki", jerseyNumber: 88, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
  { lastName: "Burrow", jerseyNumber: 9, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
  { lastName: "Brown", jerseyNumber: 30, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
  { lastName: "Ossai", jerseyNumber: 58, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
  { lastName: "Slaton Jr.", jerseyNumber: 98, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
  { lastName: "Hill", jerseyNumber: 92, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
  { lastName: "Hendrickson", jerseyNumber: 91, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
  { lastName: "Knight Jr.", jerseyNumber: 44, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
  { lastName: "Wilson", jerseyNumber: 55, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
  { lastName: "Turner II", jerseyNumber: 20, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
  { lastName: "Battle", jerseyNumber: 27, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
  { lastName: "Stone", jerseyNumber: 31, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
  { lastName: "Taylor-Britt", jerseyNumber: 29, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
  { lastName: "Hill", jerseyNumber: 23, teamPrimaryColor: "orange", teamSecondaryColor: "black" },

  // Browns
  { lastName: "Tillman", jerseyNumber: 19, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
  { lastName: "Jeudy", jerseyNumber: 3, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
  { lastName: "Thrash", jerseyNumber: 80, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
  { lastName: "Jones", jerseyNumber: 79, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
  { lastName: "Bitonio", jerseyNumber: 75, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
  { lastName: "Pocic", jerseyNumber: 55, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
  { lastName: "Teller", jerseyNumber: 77, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
  { lastName: "Conklin", jerseyNumber: 78, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
  { lastName: "Njoku", jerseyNumber: 85, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
  { lastName: "Flacco", jerseyNumber: 15, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
  { lastName: "Ford", jerseyNumber: 34, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
  { lastName: "Wright", jerseyNumber: 91, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
  { lastName: "Collins", jerseyNumber: 96, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
  { lastName: "Graham", jerseyNumber: 94, teamPrimaryColor: "brown", teamSecondaryColor: "pink" },
  { lastName: "Garrett", jerseyNumber: 95, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
  { lastName: "Bush", jerseyNumber: 30, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
  { lastName: "Schwesinger", jerseyNumber: 49, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
  { lastName: "Ward", jerseyNumber: 21, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
  { lastName: "Delpit", jerseyNumber: 9, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
  { lastName: "Hickman", jerseyNumber: 33, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
  { lastName: "Newsome II", jerseyNumber: 0, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
  { lastName: "Mitchell", jerseyNumber: 29, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },

  // Steelers
  { lastName: "Metcalf", jerseyNumber: 4, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Woods", jerseyNumber: 16, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Austin III", jerseyNumber: 19, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Jones", jerseyNumber: 77, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Seumalo", jerseyNumber: 73, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Frazier", jerseyNumber: 54, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "McCormick", jerseyNumber: 66, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Fautanu", jerseyNumber: 76, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Freiermuth", jerseyNumber: 88, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Rodgers", jerseyNumber: 8, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Warren", jerseyNumber: 30, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Thomas-Jones", jerseyNumber: 48, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Harmon", jerseyNumber: 99, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Benton", jerseyNumber: 95, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Heyward", jerseyNumber: 97, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Watt", jerseyNumber: 90, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Queen", jerseyNumber: 6, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Wilson", jerseyNumber: 41, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Highsmith", jerseyNumber: 56, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Slay", jerseyNumber: 23, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Elliott", jerseyNumber: 25, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Thornhill", jerseyNumber: 22, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Porter Jr.", jerseyNumber: 24, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
  { lastName: "Ramsey", jerseyNumber: 5, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },

  { lastName: "Odunze", jerseyNumber: 15, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
  { lastName: "Moore", jerseyNumber: 2, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
  { lastName: "Zaccheaus", jerseyNumber: 14, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
  { lastName: "Jones", jerseyNumber: 70, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
  { lastName: "Thuney", jerseyNumber: 62, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
  { lastName: "Dalman", jerseyNumber: 52, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
  { lastName: "Jackson", jerseyNumber: 73, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
  { lastName: "Wright", jerseyNumber: 58, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
  { lastName: "Loveland", jerseyNumber: 84, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
  { lastName: "Williams", jerseyNumber: 18, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
  { lastName: "Swift", jerseyNumber: 4, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
  { lastName: "Sweat", jerseyNumber: 98, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
  { lastName: "Dexter Sr.", jerseyNumber: 99, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
  { lastName: "Jarrett", jerseyNumber: 50, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
  { lastName: "Odeyingbo", jerseyNumber: 55, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
  { lastName: "Edwards", jerseyNumber: 53, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
  { lastName: "Edmunds", jerseyNumber: 49, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
  { lastName: "Stevenson", jerseyNumber: 29, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
  { lastName: "Brisker", jerseyNumber: 9, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
  { lastName: "Byard III", jerseyNumber: 31, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
  { lastName: "Johnson", jerseyNumber: 1, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
  { lastName: "Gordon", jerseyNumber: 6, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },

  { lastName: "Patrick", jerseyNumber: 12, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
  { lastName: "Williams", jerseyNumber: 1, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
  { lastName: "St. Brown", jerseyNumber: 14, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
  { lastName: "Decker", jerseyNumber: 68, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
  { lastName: "Mahogany", jerseyNumber: 73, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
  { lastName: "Glasgow", jerseyNumber: 60, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
  { lastName: "Ratledge", jerseyNumber: 69, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
  { lastName: "Sewell", jerseyNumber: 58, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
  { lastName: "LaPorta", jerseyNumber: 87, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
  { lastName: "Goff", jerseyNumber: 16, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
  { lastName: "Gibbs", jerseyNumber: 0, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },

  { lastName: "Hutchinson", jerseyNumber: 97, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
  { lastName: "Reader", jerseyNumber: 98, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
  { lastName: "McNeill", jerseyNumber: 54, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
  { lastName: "Davenport", jerseyNumber: 92, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
  { lastName: "Anzalone", jerseyNumber: 34, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
  { lastName: "Campbell", jerseyNumber: 46, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
  { lastName: "Barnes", jerseyNumber: 55, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
  { lastName: "Arnold", jerseyNumber: 6, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
  { lastName: "Branch", jerseyNumber: 32, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
  { lastName: "Joseph", jerseyNumber: 31, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
  { lastName: "Reed", jerseyNumber: 4, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
  { lastName: "Robertson", jerseyNumber: 21, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },

  { lastName: "Doubs", jerseyNumber: 87, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
  { lastName: "Golden", jerseyNumber: 22, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
  { lastName: "Reed", jerseyNumber: 11, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
  { lastName: "Walker", jerseyNumber: 63, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
  { lastName: "Banks", jerseyNumber: 65, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
  { lastName: "Jenkins", jerseyNumber: 74, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
  { lastName: "Rhyan", jerseyNumber: 75, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
  { lastName: "Tom", jerseyNumber: 50, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
  { lastName: "Kraft", jerseyNumber: 85, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
  { lastName: "Love", jerseyNumber: 10, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
  { lastName: "Jacobs", jerseyNumber: 8, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },

  { lastName: "Gary", jerseyNumber: 52, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
  { lastName: "Clark", jerseyNumber: 97, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
  { lastName: "Wyatt", jerseyNumber: 95, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
  { lastName: "Van Ness", jerseyNumber: 90, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
  { lastName: "Walker", jerseyNumber: 7, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
  { lastName: "Cooper", jerseyNumber: 56, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
  { lastName: "Hobbs", jerseyNumber: 21, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
  { lastName: "McKinney", jerseyNumber: 29, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
  { lastName: "Williams", jerseyNumber: 33, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
  { lastName: "Nixon", jerseyNumber: 25, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
  { lastName: "Bullard", jerseyNumber: 20, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },

    { lastName: "Jefferson", jerseyNumber: 18, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "Addison", jerseyNumber: 3, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "Nailor", jerseyNumber: 1, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "Darrisaw", jerseyNumber: 71, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "Jackson", jerseyNumber: 74, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "Kelly", jerseyNumber: 78, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "Fries", jerseyNumber: 76, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "O'Neill", jerseyNumber: 75, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "Hockenson", jerseyNumber: 87, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "McCarthy", jerseyNumber: 9, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "Jones Sr.", jerseyNumber: 33, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "Ham", jerseyNumber: 30, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },

  { lastName: "Allen", jerseyNumber: 93, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "Phillips", jerseyNumber: 97, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "Hargrave", jerseyNumber: 98, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "Greenard", jerseyNumber: 58, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "Cashman", jerseyNumber: 51, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "Pace Jr.", jerseyNumber: 0, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "Van Ginkel", jerseyNumber: 43, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "Rodgers", jerseyNumber: 2, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "Metellus", jerseyNumber: 44, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "Smith", jerseyNumber: 22, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "Okudah", jerseyNumber: 21, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
  { lastName: "Murphy Jr.", jerseyNumber: 7, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },

  { lastName: "Collins", jerseyNumber: 12, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "Higgins", jerseyNumber: 81, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "Kirk", jerseyNumber: 13, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "Robinson", jerseyNumber: 74, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "Tomlinson", jerseyNumber: 75, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "Patterson", jerseyNumber: 54, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "Howard", jerseyNumber: 71, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "Fisher", jerseyNumber: 57, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "Schultz", jerseyNumber: 86, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "Stroud", jerseyNumber: 7, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "Mixon", jerseyNumber: 28, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "Brooks", jerseyNumber: 44, teamPrimaryColor: "navy", teamSecondaryColor: "red" },

  { lastName: "Anderson", jerseyNumber: 51, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "Settle", jerseyNumber: 98, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "Fatukasi", jerseyNumber: 91, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "Hunter", jerseyNumber: 55, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "Harris", jerseyNumber: 48, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "Al-Shaair", jerseyNumber: 0, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "To'oTo'o", jerseyNumber: 39, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "Stingley", jerseyNumber: 24, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "Gardner-Johnson", jerseyNumber: 23, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "Bullock", jerseyNumber: 2, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "Lassiter", jerseyNumber: 4, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { lastName: "Pitre", jerseyNumber: 5, teamPrimaryColor: "navy", teamSecondaryColor: "red" },

  { lastName: "Pittman Jr.", jerseyNumber: 11, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { lastName: "Pierce", jerseyNumber: 14, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { lastName: "Downs", jerseyNumber: 1, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { lastName: "Raimann", jerseyNumber: 79, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { lastName: "Nelson", jerseyNumber: 56, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { lastName: "Bortolini", jerseyNumber: 60, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { lastName: "Goncalves", jerseyNumber: 71, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { lastName: "Smith", jerseyNumber: 72, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { lastName: "Warren", jerseyNumber: 84, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { lastName: "Richardson Sr.", jerseyNumber: 5, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { lastName: "Taylor", jerseyNumber: 28, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },

  { lastName: "Paye", jerseyNumber: 51, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { lastName: "Stewart", jerseyNumber: 90, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { lastName: "Buckner", jerseyNumber: 99, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { lastName: "Latu", jerseyNumber: 97, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { lastName: "McGrone", jerseyNumber: 59, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { lastName: "Franklin", jerseyNumber: 44, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { lastName: "Ward", jerseyNumber: 7, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { lastName: "Cross", jerseyNumber: 20, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { lastName: "Bynum", jerseyNumber: 0, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { lastName: "Walley", jerseyNumber: 27, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { lastName: "Moore II", jerseyNumber: 23, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },

  { lastName: "Jefferson", jerseyNumber: 11, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { lastName: "Ridley", jerseyNumber: 0, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { lastName: "Lockett", jerseyNumber: 4, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { lastName: "Moore Jr.", jerseyNumber: 75, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { lastName: "Skoronski", jerseyNumber: 77, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { lastName: "Cushenberry III", jerseyNumber: 79, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { lastName: "Zeitler", jerseyNumber: 70, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { lastName: "Latham", jerseyNumber: 55, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { lastName: "Okonkwo", jerseyNumber: 85, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { lastName: "Ward", jerseyNumber: 1, teamPrimaryColor: "lightblue", teamSecondaryColor: "pink" },
  { lastName: "Pollard", jerseyNumber: 20, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },

  { lastName: "Joseph-Day", jerseyNumber: 69, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { lastName: "Sweat", jerseyNumber: 93, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { lastName: "Simmons", jerseyNumber: 98, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { lastName: "Jones", jerseyNumber: 45, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { lastName: "Barton", jerseyNumber: 50, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { lastName: "Williams Sr.", jerseyNumber: 52, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { lastName: "Key", jerseyNumber: 49, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { lastName: "Sneed", jerseyNumber: 38, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { lastName: "Hooker", jerseyNumber: 37, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { lastName: "Woods", jerseyNumber: 25, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { lastName: "Brownlee Jr.", jerseyNumber: 29, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { lastName: "McCreary", jerseyNumber: 21, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },

  { lastName: "Thomas Jr.", jerseyNumber: 7, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { lastName: "Brown", jerseyNumber: 5, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { lastName: "Hunter", jerseyNumber: 12, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { lastName: "Little", jerseyNumber: 72, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { lastName: "Cleveland", jerseyNumber: 76, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { lastName: "Hainsey", jerseyNumber: 73, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { lastName: "Mekari", jerseyNumber: 65, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { lastName: "Harrison", jerseyNumber: 77, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { lastName: "Strange", jerseyNumber: 85, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { lastName: "Lawrence", jerseyNumber: 16, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { lastName: "Etienne Jr.", jerseyNumber: 1, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },

  { lastName: "Walker", jerseyNumber: 44, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { lastName: "Hamilton", jerseyNumber: 52, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { lastName: "Armstead", jerseyNumber: 91, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { lastName: "Hines-Allen", jerseyNumber: 41, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { lastName: "Oluokun", jerseyNumber: 23, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { lastName: "Lloyd", jerseyNumber: 0, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { lastName: "Abdullah", jerseyNumber: 56, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { lastName: "Jones", jerseyNumber: 22, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { lastName: "Murray", jerseyNumber: 29, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { lastName: "Savage", jerseyNumber: 6, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { lastName: "Campbell", jerseyNumber: 3, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { lastName: "Lewis", jerseyNumber: 2, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },

  { lastName: "Mooney", jerseyNumber: 1, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "London", jerseyNumber: 5, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "McCloud", jerseyNumber: 34, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "Matthews", jerseyNumber: 70, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "Bergeron", jerseyNumber: 65, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "Neuzil", jerseyNumber: 64, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "Lindstrom", jerseyNumber: 63, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "McGary", jerseyNumber: 76, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "Pitts", jerseyNumber: 8, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "Penix", jerseyNumber: 9, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "Robinson", jerseyNumber: 7, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "Orhorhoro", jerseyNumber: 98, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "Onyemata", jerseyNumber: 90, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "Harrison", jerseyNumber: 96, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "Pearce", jerseyNumber: 27, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "Deablo", jerseyNumber: 0, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "Elliss", jerseyNumber: 55, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "Floyd", jerseyNumber: 56, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "Hughes", jerseyNumber: 21, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "Bates", jerseyNumber: 3, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "Fuller", jerseyNumber: 29, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "Terrell", jerseyNumber: 24, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { lastName: "Alford", jerseyNumber: 20, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },

  { lastName: "McMillan", jerseyNumber: 4, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Leggette", jerseyNumber: 17, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Thielen", jerseyNumber: 19, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Ekwonu", jerseyNumber: 79, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Lewis", jerseyNumber: 68, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Corbett", jerseyNumber: 63, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Hunt", jerseyNumber: 50, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Moton", jerseyNumber: 72, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Tremble", jerseyNumber: 82, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Young", jerseyNumber: 9, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Hubbard", jerseyNumber: 30, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Brown", jerseyNumber: 95, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Brown", jerseyNumber: 97, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Wharton", jerseyNumber: 92, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Jones", jerseyNumber: 91, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Wallace", jerseyNumber: 32, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Rozeboom", jerseyNumber: 56, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Wonnum", jerseyNumber: 98, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Jackson", jerseyNumber: 2, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Moehrig", jerseyNumber: 7, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Richardson", jerseyNumber: 36, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Horn", jerseyNumber: 8, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { lastName: "Smith-Wade", jerseyNumber: 26, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },

  { lastName: "Olave", jerseyNumber: 12, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { lastName: "Cooks", jerseyNumber: 10, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { lastName: "Shaheed", jerseyNumber: 22, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { lastName: "Banks", jerseyNumber: 71, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { lastName: "Penning", jerseyNumber: 70, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { lastName: "McCoy", jerseyNumber: 78, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { lastName: "Ruiz", jerseyNumber: 51, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { lastName: "Fuaga", jerseyNumber: 75, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { lastName: "Johnson", jerseyNumber: 83, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { lastName: "Rattler", jerseyNumber: 2, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { lastName: "Kamara", jerseyNumber: 41, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { lastName: "Shepherd", jerseyNumber: 93, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { lastName: "Godchaux", jerseyNumber: 92, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { lastName: "Bresee", jerseyNumber: 90, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { lastName: "Young", jerseyNumber: 99, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { lastName: "Werner", jerseyNumber: 20, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { lastName: "Davis", jerseyNumber: 56, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { lastName: "Granderson", jerseyNumber: 96, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { lastName: "Yiadom", jerseyNumber: 27, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { lastName: "Reid", jerseyNumber: 21, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { lastName: "Blackmon", jerseyNumber: 28, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { lastName: "McKinstry", jerseyNumber: 4, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },

  { lastName: "Evans", jerseyNumber: 13, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "Godwin", jerseyNumber: 14, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "Egbuka", jerseyNumber: 9, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "Wirfs", jerseyNumber: 78, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "Bredeson", jerseyNumber: 68, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "Barton", jerseyNumber: 62, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "Mauch", jerseyNumber: 69, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "Goedeke", jerseyNumber: 67, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "Otton", jerseyNumber: 88, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "Mayfield", jerseyNumber: 6, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "Irving", jerseyNumber: 7, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "Hall", jerseyNumber: 90, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "Vea", jerseyNumber: 50, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "Kancey", jerseyNumber: 94, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "Reddick", jerseyNumber: 5, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "David", jerseyNumber: 54, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "Dennis", jerseyNumber: 8, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "Diaby", jerseyNumber: 0, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "McCollum", jerseyNumber: 27, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "Smith", jerseyNumber: 23, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "Winfield", jerseyNumber: 31, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "Dean", jerseyNumber: 35, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { lastName: "Izien", jerseyNumber: 29, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },

  { lastName: "Sutton", jerseyNumber: 14, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "Mims", jerseyNumber: 19, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "Vele", jerseyNumber: 17, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "Bolles", jerseyNumber: 72, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "Powers", jerseyNumber: 74, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "Wattenberg", jerseyNumber: 60, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "Meinerz", jerseyNumber: 77, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "McGlinchey", jerseyNumber: 69, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "Engram", jerseyNumber: 1, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "Nix", jerseyNumber: 10, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "Harvey", jerseyNumber: 37, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "Allen", jerseyNumber: 99, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "Jones", jerseyNumber: 93, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "Franklin-Myers", jerseyNumber: 98, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "Cooper", jerseyNumber: 0, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "Greenlaw", jerseyNumber: 57, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "Singleton", jerseyNumber: 49, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "Bonitto", jerseyNumber: 15, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "Surtain", jerseyNumber: 2, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "Hufanga", jerseyNumber: 9, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "Jones", jerseyNumber: 22, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "Moss", jerseyNumber: 21, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { lastName: "Barron", jerseyNumber: 12, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },

  { lastName: "Worthy", jerseyNumber: 1, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { lastName: "Brown", jerseyNumber: 5, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { lastName: "Rice", jerseyNumber: 4, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { lastName: "Simmons", jerseyNumber: 71, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { lastName: "Suamataia", jerseyNumber: 76, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { lastName: "Humphrey", jerseyNumber: 52, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { lastName: "Smith", jerseyNumber: 65, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { lastName: "Taylor", jerseyNumber: 74, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { lastName: "Kelce", jerseyNumber: 87, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { lastName: "Mahomes", jerseyNumber: 15, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { lastName: "Pacheco", jerseyNumber: 10, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { lastName: "Karlaftis", jerseyNumber: 56, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { lastName: "Jones", jerseyNumber: 95, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { lastName: "Pennel", jerseyNumber: 69, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { lastName: "Danna", jerseyNumber: 51, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { lastName: "Tranquill", jerseyNumber: 23, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { lastName: "Bolton", jerseyNumber: 32, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { lastName: "Chenal", jerseyNumber: 54, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { lastName: "Watson", jerseyNumber: 35, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { lastName: "Hicks", jerseyNumber: 21, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { lastName: "Cook", jerseyNumber: 6, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { lastName: "Fulton", jerseyNumber: 8, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { lastName: "McDuffie", jerseyNumber: 22, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },

  { lastName: "Thornton", jerseyNumber: 10, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { lastName: "Tucker", jerseyNumber: 1, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { lastName: "Meyers", jerseyNumber: 16, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { lastName: "Miller", jerseyNumber: 74, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { lastName: "Parham", jerseyNumber: 66, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { lastName: "Meredith", jerseyNumber: 61, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { lastName: "Powers-Johnson", jerseyNumber: 58, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { lastName: "Glaze", jerseyNumber: 71, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { lastName: "Bowers", jerseyNumber: 89, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { lastName: "Smith", jerseyNumber: 7, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { lastName: "Jeanty", jerseyNumber: 2, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { lastName: "Crosby", jerseyNumber: 98, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { lastName: "Butler", jerseyNumber: 69, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { lastName: "Laulu", jerseyNumber: 96, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { lastName: "Koonce", jerseyNumber: 51, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { lastName: "Pratt", jerseyNumber: 57, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { lastName: "Roberts", jerseyNumber: 52, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { lastName: "Chinn", jerseyNumber: 11, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { lastName: "Pola-Mao", jerseyNumber: 20, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { lastName: "Porter", jerseyNumber: 26, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { lastName: "Stokes", jerseyNumber: 22, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { lastName: "Holmes", jerseyNumber: 30, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },

  { lastName: "Harris", jerseyNumber: 9, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "Johnston", jerseyNumber: 1, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "McConkey", jerseyNumber: 15, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "Slater", jerseyNumber: 70, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "Bozeman", jerseyNumber: 75, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "Johnson", jerseyNumber: 77, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "Becton", jerseyNumber: 73, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "Alt", jerseyNumber: 76, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "Dissly", jerseyNumber: 89, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "Herbert", jerseyNumber: 10, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "Hampton", jerseyNumber: 8, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "Hand", jerseyNumber: 91, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "Tart", jerseyNumber: 90, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "Ogbonnia", jerseyNumber: 93, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "Tuipulotu", jerseyNumber: 45, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "Perryman", jerseyNumber: 6, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "Henley", jerseyNumber: 0, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "Mack", jerseyNumber: 52, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "Jackson", jerseyNumber: 26, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "James", jerseyNumber: 3, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "Gilman", jerseyNumber: 32, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "Hart", jerseyNumber: 20, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { lastName: "Still", jerseyNumber: 29, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },

  { lastName: "Campbell", jerseyNumber: 93, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Tomlinson", jerseyNumber: 94, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Robinson", jerseyNumber: 56, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Browning", jerseyNumber: 5, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Davis-Gaither", jerseyNumber: 27, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Wilson Sr.", jerseyNumber: 2, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Sweat", jerseyNumber: 10, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Johnson", jerseyNumber: 0, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Thompson", jerseyNumber: 34, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Baker", jerseyNumber: 3, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Melton", jerseyNumber: 16, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Williams", jerseyNumber: 21, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Harrison", jerseyNumber: 18, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Wilson", jerseyNumber: 14, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Dortch", jerseyNumber: 4, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Johnson", jerseyNumber: 70, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Brown", jerseyNumber: 63, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Froholdt", jerseyNumber: 72, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Adams", jerseyNumber: 74, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Williams", jerseyNumber: 73, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "McBride", jerseyNumber: 85, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Murray", jerseyNumber: 1, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { lastName: "Conner", jerseyNumber: 6, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },

  { lastName: "Fiske", jerseyNumber: 55, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Ford", jerseyNumber: 95, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Turner", jerseyNumber: 91, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Young", jerseyNumber: 0, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Landman", jerseyNumber: 53, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Speights", jerseyNumber: 48, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Verse", jerseyNumber: 8, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Williams", jerseyNumber: 31, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Curl", jerseyNumber: 3, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Kinchens", jerseyNumber: 26, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Witherspoon", jerseyNumber: 4, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Lake", jerseyNumber: 37, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Adams", jerseyNumber: 17, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Nacua", jerseyNumber: 12, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Atwell", jerseyNumber: 5, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Jackson", jerseyNumber: 77, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Avila", jerseyNumber: 73, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Shelton", jerseyNumber: 65, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Dotson", jerseyNumber: 69, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Havenstein", jerseyNumber: 79, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Higbee", jerseyNumber: 89, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Stafford", jerseyNumber: 9, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { lastName: "Williams", jerseyNumber: 23, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },

  { lastName: "Bosa", jerseyNumber: 97, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "Elliott", jerseyNumber: 92, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "Givens", jerseyNumber: 90, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "Williams", jerseyNumber: 98, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "Winters", jerseyNumber: 53, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "Warner", jerseyNumber: 54, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "Green", jerseyNumber: 0, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "Grant", jerseyNumber: 24, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "Pinnock", jerseyNumber: 25, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "Lenoir", jerseyNumber: 2, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "Stout", jerseyNumber: 20, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "Aiyuk", jerseyNumber: 11, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "Pearsall", jerseyNumber: 1, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "Jennings", jerseyNumber: 15, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "Williams", jerseyNumber: 71, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "Bartch", jerseyNumber: 78, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "Brendel", jerseyNumber: 64, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "Puni", jerseyNumber: 77, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "McKivitz", jerseyNumber: 68, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "Kittle", jerseyNumber: 85, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "Purdy", jerseyNumber: 13, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "McCaffrey", jerseyNumber: 23, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { lastName: "Juszczyk", jerseyNumber: 44, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },

  { lastName: "Williams", jerseyNumber: 99, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Murphy II", jerseyNumber: 91, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Reed", jerseyNumber: 90, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Lawrence", jerseyNumber: 0, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Knight", jerseyNumber: 48, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Jones IV", jerseyNumber: 13, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Nwosu", jerseyNumber: 7, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Jobe", jerseyNumber: 29, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Love", jerseyNumber: 20, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Bryant", jerseyNumber: 8, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Woolen", jerseyNumber: 27, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Witherspoon", jerseyNumber: 21, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Smith-Njigba", jerseyNumber: 11, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Valdes-Scantling", jerseyNumber: 1, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Kupp", jerseyNumber: 10, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Cross", jerseyNumber: 67, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Zabel", jerseyNumber: 76, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Oluwatimi", jerseyNumber: 55, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Haynes", jerseyNumber: 64, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Lucas", jerseyNumber: 72, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Barner", jerseyNumber: 88, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Darnold", jerseyNumber: 14, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Walker", jerseyNumber: 9, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { lastName: "Ouzts", jerseyNumber: 40, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },







];