export type OnTheClock = {
    firstName: string
    lastName: string
    year: number
    round: number
    pick: number
    position: string
    team: string
    division: string
    college: string
}

export const onTheClockPlayers: OnTheClock[] = [
  { firstName: "Cam", lastName: "Ward", year: 2025, round: 1, pick: 1, position: "QB", team: "TEN", division: "AFC South", college: "Miami (FL)" },
  { firstName: "Travis", lastName: "Hunter", year: 2025, round: 1, pick: 2, position: "WR", team: "JAX", division: "AFC South", college: "Colorado" },
  { firstName: "Abdul", lastName: "Carter", year: 2025, round: 1, pick: 3, position: "LB", team: "NYG", division: "NFC East", college: "Penn State" },
  { firstName: "Will", lastName: "Campbell", year: 2025, round: 1, pick: 4, position: "OT", team: "NWE", division: "AFC East", college: "LSU" },
  { firstName: "Mason", lastName: "Graham", year: 2025, round: 1, pick: 5, position: "DT", team: "CLE", division: "AFC North", college: "Michigan" },
  { firstName: "Amarius", lastName: "Mims", year: 2025, round: 1, pick: 8, position: "OT", team: "ARI", division: "NFC West", college: "Georgia" },
  { firstName: "Tyler", lastName: "Booker", year: 2025, round: 1, pick: 12, position: "OL", team: "DAL", division: "NFC East", college: "Alabama" },
  { firstName: "Kenneth", lastName: "Grant", year: 2025, round: 1, pick: 13, position: "DT", team: "MIA", division: "AFC East", college: "Michigan" },
  { firstName: "Jalon", lastName: "Walker", year: 2025, round: 1, pick: 15, position: "DE", team: "ATL", division: "NFC South", college: "Georgia" },
  { firstName: "Walter", lastName: "Nolen", year: 2025, round: 1, pick: 16, position: "DT", team: "ARI", division: "NFC West", college: "Ole Miss" },
  { firstName: "Shemar", lastName: "Stewart", year: 2025, round: 1, pick: 17, position: "DL", team: "CIN", division: "AFC North", college: "Texas A&M" },
  { firstName: "Emeka", lastName: "Egbuka", year: 2025, round: 1, pick: 19, position: "WR", team: "TAM", division: "NFC South", college: "Ohio State" },
  { firstName: "Donovan", lastName: "Jackson", year: 2025, round: 1, pick: 24, position: "OL", team: "NYG", division: "NFC East", college: "Ohio State" },
  { firstName: "James", lastName: "Pearce", year: 2025, round: 1, pick: 26, position: "DE", team: "ATL", division: "NFC South", college: "Tennessee" },
  { firstName: "Jaxson", lastName: "Dart", year: 2025, round: 1, pick: 25, position: "QB", team: "NYJ", division: "AFC East", college: "Ole Miss" },
  { firstName: "Tyleik", lastName: "Williams", year: 2025, round: 1, pick: 28, position: "DT", team: "MIA", division: "AFC East", college: "Ohio State" },
  { firstName: "JT", lastName: "Tuimoloau", year: 2025, round: 1, pick: 30, position: "DE", team: "BUF", division: "AFC East", college: "Ohio State" },
  { firstName: "Nick", lastName: "Emmanwori", year: 2025, round: 2, pick: 35, position: "S", team: "SEA", division: "NFC West", college: "South Carolina" },
  { firstName: "Quinshon", lastName: "Judkins", year: 2025, round: 2, pick: 36, position: "RB", team: "CLE", division: "AFC North", college: "Ohio State" },
  { firstName: "Jonah", lastName: "Savaiinaea", year: 2025, round: 2, pick: 37, position: "OL", team: "MIA", division: "AFC East", college: "Arizona" },
  { firstName: "Caleb", lastName: "Williams", year: 2024, round: 1, pick: 1, position: "QB", team: "CHI", division: "NFC North", college: "USC" },
  { firstName: "Jayden", lastName: "Daniels", year: 2024, round: 1, pick: 2, position: "QB", team: "WAS", division: "NFC East", college: "LSU" },
  { firstName: "Drake", lastName: "Maye", year: 2024, round: 1, pick: 3, position: "QB", team: "NWE", division: "AFC East", college: "North Carolina" },
  { firstName: "Marvin", lastName: "Harrison Jr.", year: 2024, round: 1, pick: 4, position: "WR", team: "ARI", division: "NFC West", college: "Ohio State" },
  { firstName: "Joe", lastName: "Alt", year: 2024, round: 1, pick: 5, position: "OT", team: "LAC", division: "AFC West", college: "Notre Dame" },
  { firstName: "Malik", lastName: "Nabers", year: 2024, round: 1, pick: 6, position: "WR", team: "NYG", division: "NFC East", college: "LSU" },
  { firstName: "JC", lastName: "Latham", year: 2024, round: 1, pick: 7, position: "OT", team: "TEN", division: "AFC South", college: "Alabama" },
  { firstName: "Michael", lastName: "Penix", year: 2024, round: 1, pick: 8, position: "QB", team: "ATL", division: "NFC South", college: "Washington" },
  { firstName: "Rome", lastName: "Odunze", year: 2024, round: 1, pick: 9, position: "WR", team: "CHI", division: "NFC North", college: "Washington" },
  { firstName: "J.J.", lastName: "McCarthy", year: 2024, round: 1, pick: 10, position: "QB", team: "MIN", division: "NFC North", college: "Michigan" },
  { firstName: "Olumuyiwa", lastName: "Fashanu", year: 2024, round: 1, pick: 11, position: "OT", team: "NYJ", division: "AFC East", college: "Penn State" },
  { firstName: "Bo", lastName: "Nix", year: 2024, round: 1, pick: 12, position: "QB", team: "DEN", division: "AFC West", college: "Oregon" },
  { firstName: "Brock", lastName: "Bowers", year: 2024, round: 1, pick: 13, position: "TE", team: "LVR", division: "AFC West", college: "Georgia" },
  { firstName: "Laiatu", lastName: "Latu", year: 2024, round: 1, pick: 15, position: "DL", team: "IND", division: "AFC South", college: "UCLA" },
  { firstName: "Dallas", lastName: "Turner", year: 2024, round: 1, pick: 17, position: "LB", team: "MIN", division: "NFC North", college: "Alabama" },
  { firstName: "Amarius", lastName: "Mims", year: 2024, round: 1, pick: 18, position: "OT", team: "CIN", division: "AFC North", college: "Georgia" },
  { firstName: "Jared", lastName: "Verse", year: 2024, round: 1, pick: 19, position: "DE", team: "LAR", division: "NFC West", college: "Florida State" },
  { firstName: "Troy", lastName: "Fautanu", year: 2024, round: 1, pick: 20, position: "OT", team: "PIT", division: "AFC North", college: "Washington" },
  { firstName: "Chop", lastName: "Robinson", year: 2024, round: 1, pick: 21, position: "DL", team: "MIA", division: "AFC East", college: "Penn State" },
  { firstName: "Quinyon", lastName: "Mitchell", year: 2024, round: 1, pick: 22, position: "CB", team: "PHI", division: "NFC East", college: "Toledo" },
  { firstName: "Brian", lastName: "Thomas", year: 2024, round: 1, pick: 23, position: "WR", team: "JAX", division: "AFC South", college: "LSU" },
  { firstName: "Terrion", lastName: "Arnold", year: 2024, round: 1, pick: 24, position: "CB", team: "DET", division: "NFC North", college: "Alabama" },
  { firstName: "Jordan", lastName: "Morgan", year: 2024, round: 1, pick: 25, position: "OL", team: "GNB", division: "NFC North", college: "Arizona" },
  { firstName: "Graham", lastName: "Barton", year: 2024, round: 1, pick: 26, position: "OL", team: "TAM", division: "NFC South", college: "Duke" },
  { firstName: "Darius", lastName: "Robinson", year: 2024, round: 1, pick: 27, position: "DL", team: "ARI", division: "NFC West", college: "Missouri" },
  { firstName: "Xavier", lastName: "Worthy", year: 2024, round: 1, pick: 28, position: "WR", team: "KAN", division: "AFC West", college: "Texas" },
  { firstName: "Tyler", lastName: "Guyton", year: 2024, round: 1, pick: 29, position: "OT", team: "DAL", division: "NFC East", college: "Oklahoma" },
  { firstName: "Xavier", lastName: "Legette", year: 2024, round: 1, pick: 32, position: "WR", team: "CAR", division: "NFC South", college: "South Carolina" },
  { firstName: "Keon", lastName: "Coleman", year: 2024, round: 2, pick: 33, position: "WR", team: "BUF", division: "AFC East", college: "Florida State" },
  { firstName: "Ladd", lastName: "McConkey", year: 2024, round: 2, pick: 34, position: "WR", team: "LAC", division: "AFC West", college: "Georgia" },
  { firstName: "Ruke", lastName: "Orhorhoro", year: 2024, round: 2, pick: 35, position: "DT", team: "ATL", division: "NFC South", college: "Clemson" },
  { firstName: "Ja'Lynn", lastName: "Polk", year: 2024, round: 2, pick: 37, position: "WR", team: "NWE", division: "AFC East", college: "Washington" },
  { firstName: "T'Vondre", lastName: "Sweat", year: 2024, round: 2, pick: 38, position: "DL", team: "TEN", division: "AFC South", college: "Texas" },
  { firstName: "Kool-Aid", lastName: "McKinstry", year: 2024, round: 2, pick: 41, position: "CB", team: "NOR", division: "NFC South", college: "Alabama" },
  { firstName: "Kamari", lastName: "Lassiter", year: 2024, round: 2, pick: 42, position: "CB", team: "ATL", division: "NFC South", college: "Georgia" },
  { firstName: "Max", lastName: "Melton", year: 2024, round: 2, pick: 43, position: "CB", team: "ARI", division: "NFC West", college: "Rutgers" },
  { firstName: "Bryce", lastName: "Young", year: 2023, round: 1, pick: 1, position: "QB", team: "CAR", division: "NFC South", college: "Alabama" },
  { firstName: "C.J.", lastName: "Stroud", year: 2023, round: 1, pick: 2, position: "QB", team: "HOU", division: "AFC South", college: "Ohio State" },
  { firstName: "Will", lastName: "Anderson", year: 2023, round: 1, pick: 3, position: "LB", team: "HOU", division: "AFC South", college: "Alabama" },
  { firstName: "Anthony", lastName: "Richardson", year: 2023, round: 1, pick: 4, position: "QB", team: "IND", division: "AFC South", college: "Florida" },
  { firstName: "Devon", lastName: "Witherspoon", year: 2023, round: 1, pick: 5, position: "CB", team: "SEA", division: "NFC West", college: "Illinois" },
  { firstName: "Paris", lastName: "Johnson", year: 2023, round: 1, pick: 6, position: "OT", team: "ARI", division: "NFC West", college: "Ohio State" },
  { firstName: "Tyree", lastName: "Wilson", year: 2023, round: 1, pick: 7, position: "DL", team: "LVR", division: "AFC West", college: "Texas Tech" },
  { firstName: "Bijan", lastName: "Robinson", year: 2023, round: 1, pick: 8, position: "RB", team: "ATL", division: "NFC South", college: "Texas" },
  { firstName: "Jalen", lastName: "Carter", year: 2023, round: 1, pick: 9, position: "DL", team: "PHI", division: "NFC East", college: "Georgia" },
  { firstName: "Darnell", lastName: "Wright", year: 2023, round: 1, pick: 10, position: "OT", team: "CHI", division: "NFC North", college: "Tennessee" },
  { firstName: "Peter", lastName: "Skoronski", year: 2023, round: 1, pick: 11, position: "OL", team: "TEN", division: "AFC South", college: "Northwestern" },
  { firstName: "Jahmyr", lastName: "Gibbs", year: 2023, round: 1, pick: 12, position: "RB", team: "DET", division: "NFC North", college: "Alabama" },
  { firstName: "Lukas", lastName: "Van Ness", year: 2023, round: 1, pick: 13, position: "DL", team: "GNB", division: "NFC North", college: "Iowa" },
  { firstName: "Broderick", lastName: "Jones", year: 2023, round: 1, pick: 14, position: "OT", team: "PIT", division: "AFC North", college: "Georgia" },
  { firstName: "Will", lastName: "McDonald", year: 2023, round: 1, pick: 15, position: "DE", team: "NYJ", division: "AFC East", college: "Iowa State" },
  { firstName: "Emmanuel", lastName: "Forbes", year: 2023, round: 1, pick: 16, position: "CB", team: "WAS", division: "NFC East", college: "Mississippi State" },
  { firstName: "Christian", lastName: "Gonzalez", year: 2023, round: 1, pick: 17, position: "CB", team: "NE", division: "AFC East", college: "Oregon" },
  { firstName: "Jack", lastName: "Campbell", year: 2023, round: 1, pick: 18, position: "LB", team: "DET", division: "NFC North", college: "Iowa" },
  { firstName: "Calijah", lastName: "Kancey", year: 2023, round: 1, pick: 19, position: "DT", team: "TAM", division: "NFC South", college: "Pittsburgh" },
  { firstName: "Jaxon", lastName: "Smith-Njigba", year: 2023, round: 1, pick: 20, position: "WR", team: "SEA", division: "NFC West", college: "Ohio State" },
  { firstName: "Quentin", lastName: "Johnston", year: 2023, round: 1, pick: 21, position: "WR", team: "LAC", division: "AFC West", college: "TCU" },
  { firstName: "Zay", lastName: "Flowers", year: 2023, round: 1, pick: 22, position: "WR", team: "BAL", division: "AFC North", college: "Boston College" },
  { firstName: "Jordan", lastName: "Addison", year: 2023, round: 1, pick: 23, position: "WR", team: "MIN", division: "NFC North", college: "USC" },
  { firstName: "Deonte", lastName: "Banks", year: 2023, round: 1, pick: 24, position: "CB", team: "NYG", division: "NFC East", college: "Maryland" },
  { firstName: "Dalton", lastName: "Kincaid", year: 2023, round: 1, pick: 25, position: "TE", team: "BUF", division: "AFC East", college: "Utah" },
  { firstName: "Mazi", lastName: "Smith", year: 2023, round: 1, pick: 26, position: "DL", team: "DAL", division: "NFC East", college: "Michigan" },
  { firstName: "Anton", lastName: "Harrison", year: 2023, round: 1, pick: 27, position: "OL", team: "JAX", division: "AFC South", college: "Oklahoma" },
  { firstName: "Myles", lastName: "Murphy", year: 2023, round: 1, pick: 28, position: "DE", team: "CIN", division: "AFC North", college: "Clemson" },
  { firstName: "Nolan", lastName: "Smith", year: 2023, round: 1, pick: 30, position: "LB", team: "PHI", division: "NFC East", college: "Georgia" },
  { firstName: "Felix", lastName: "Anudike-Uzomah", year: 2023, round: 1, pick: 31, position: "DE", team: "KAN", division: "AFC West", college: "Kansas State" },
  { firstName: "Joey", lastName: "Porter Jr.", year: 2023, round: 2, pick: 32, position: "CB", team: "PIT", division: "AFC North", college: "Penn State" },
  { firstName: "Will", lastName: "Levis", year: 2023, round: 2, pick: 33, position: "QB", team: "TEN", division: "AFC South", college: "Kentucky" },
  { firstName: "Sam", lastName: "LaPorta", year: 2023, round: 2, pick: 34, position: "TE", team: "DET", division: "NFC North", college: "Iowa" },
  { firstName: "Michael", lastName: "Mayer", year: 2023, round: 2, pick: 35, position: "TE", team: "LVR", division: "AFC West", college: "Notre Dame" },
  { firstName: "Steve", lastName: "Avila", year: 2023, round: 2, pick: 36, position: "OL", team: "LAR", division: "NFC West", college: "TCU" },
  { firstName: "Derrick", lastName: "Hall", year: 2023, round: 2, pick: 37, position: "DE", team: "SEA", division: "NFC West", college: "Auburn" },
  { firstName: "Matthew", lastName: "Bergeron", year: 2023, round: 2, pick: 38, position: "OL", team: "ATL", division: "NFC South", college: "Syracuse" },
  { firstName: "Jonathan", lastName: "Mingo", year: 2023, round: 2, pick: 39, position: "WR", team: "CAR", division: "NFC South", college: "Ole Miss" },
  { firstName: "B.J.", lastName: "Ojulari", year: 2023, round: 2, pick: 41, position: "LB", team: "ARI", division: "NFC West", college: "LSU" },
  { firstName: "Luke", lastName: "Musgrave", year: 2023, round: 2, pick: 42, position: "TE", team: "GNB", division: "NFC North", college: "Oregon State" },
  { firstName: "Joe", lastName: "Tippmann", year: 2023, round: 2, pick: 43, position: "OL", team: "NYJ", division: "AFC East", college: "Wisconsin" },
  { firstName: "Puka", lastName: "Nacua", year: 2023, round: 5, pick: 177, position: "WR", team: "LAR", division: "NFC West", college: "BYU" },
  { firstName: "De'Von", lastName: "Achane", year: 2023, round: 3, pick: 84, position: "RB", team: "MIA", division: "AFC East", college: "Texas A&M" },
  { firstName: "Tank", lastName: "Dell", year: 2023, round: 3, pick: 69, position: "WR", team: "HOU", division: "AFC South", college: "Houston" },
  { firstName: "Chase", lastName: "Brown", year: 2023, round: 5, pick: 163, position: "RB", team: "CIN", division: "AFC North", college: "Illinois" },
  { firstName: "Roschon", lastName: "Johnson", year: 2023, round: 4, pick: 115, position: "RB", team: "CHI", division: "NFC North", college: "Texas" },
  { firstName: "Travon", lastName: "Walker", year: 2022, round: 1, pick: 1, position: "DE", team: "JAX", division: "AFC South", college: "Georgia" },
  { firstName: "Aidan", lastName: "Hutchinson", year: 2022, round: 1, pick: 2, position: "DE", team: "DET", division: "NFC North", college: "Michigan" },
  { firstName: "Derek", lastName: "Stingley Jr.", year: 2022, round: 1, pick: 3, position: "CB", team: "HOU", division: "AFC South", college: "LSU" },
  { firstName: "Sauce", lastName: "Gardner", year: 2022, round: 1, pick: 4, position: "CB", team: "NYJ", division: "AFC East", college: "Cincinnati" },
  { firstName: "Kayvon", lastName: "Thibodeaux", year: 2022, round: 1, pick: 5, position: "DE", team: "NYG", division: "NFC East", college: "Oregon" },
  { firstName: "Ikem", lastName: "Ekwonu", year: 2022, round: 1, pick: 6, position: "OT", team: "CAR", division: "NFC South", college: "NC State" },
  { firstName: "Evan", lastName: "Neal", year: 2022, round: 1, pick: 7, position: "OT", team: "NYG", division: "NFC East", college: "Alabama" },
  { firstName: "Drake", lastName: "London", year: 2022, round: 1, pick: 8, position: "WR", team: "ATL", division: "NFC South", college: "USC" },
  { firstName: "Charles", lastName: "Cross", year: 2022, round: 1, pick: 9, position: "OT", team: "SEA", division: "NFC West", college: "Mississippi State" },
  { firstName: "Garrett", lastName: "Wilson", year: 2022, round: 1, pick: 10, position: "WR", team: "NYJ", division: "AFC East", college: "Ohio State" },
  { firstName: "Chris", lastName: "Olave", year: 2022, round: 1, pick: 11, position: "WR", team: "NOR", division: "NFC South", college: "Ohio State" },
  { firstName: "Jameson", lastName: "Williams", year: 2022, round: 1, pick: 12, position: "WR", team: "DET", division: "NFC North", college: "Alabama" },
  { firstName: "Jordan", lastName: "Davis", year: 2022, round: 1, pick: 13, position: "DT", team: "PHI", division: "NFC East", college: "Georgia" },
  { firstName: "Kyle", lastName: "Hamilton", year: 2022, round: 1, pick: 14, position: "S", team: "BAL", division: "AFC North", college: "Notre Dame" },
  { firstName: "Kenyon", lastName: "Green", year: 2022, round: 1, pick: 15, position: "OL", team: "HOU", division: "AFC South", college: "Texas A&M" },
  { firstName: "Jahan", lastName: "Dotson", year: 2022, round: 1, pick: 16, position: "WR", team: "WAS", division: "NFC East", college: "Penn State" },
  { firstName: "Zion", lastName: "Johnson", year: 2022, round: 1, pick: 17, position: "G", team: "LAC", division: "AFC West", college: "Boston College" },
  { firstName: "Treylon", lastName: "Burks", year: 2022, round: 1, pick: 18, position: "WR", team: "TEN", division: "AFC South", college: "Arkansas" },
  { firstName: "Kenny", lastName: "Pickett", year: 2022, round: 1, pick: 20, position: "QB", team: "PIT", division: "AFC North", college: "Pittsburgh" },
  { firstName: "Trent", lastName: "McDuffie", year: 2022, round: 1, pick: 21, position: "CB", team: "KAN", division: "AFC West", college: "Washington" },
  { firstName: "Quay", lastName: "Walker", year: 2022, round: 1, pick: 22, position: "LB", team: "GNB", division: "NFC North", college: "Georgia" },
  { firstName: "Kaiir", lastName: "Elam", year: 2022, round: 1, pick: 23, position: "CB", team: "BUF", division: "AFC East", college: "Florida" },
  { firstName: "Tyler", lastName: "Smith", year: 2022, round: 1, pick: 24, position: "OT", team: "DAL", division: "NFC East", college: "Tulsa" },
  { firstName: "Tyler", lastName: "Linderbaum", year: 2022, round: 1, pick: 25, position: "C", team: "BAL", division: "AFC North", college: "Iowa" },
  { firstName: "Jermaine", lastName: "Johnson II", year: 2022, round: 1, pick: 26, position: "LB", team: "NYJ", division: "AFC East", college: "Florida State" },
  { firstName: "Devin", lastName: "Lloyd", year: 2022, round: 1, pick: 27, position: "LB", team: "JAX", division: "AFC South", college: "Utah" },
  { firstName: "Devonte", lastName: "Wyatt", year: 2022, round: 1, pick: 28, position: "DT", team: "GNB", division: "NFC North", college: "Georgia" },
  { firstName: "Cole", lastName: "Strange", year: 2022, round: 1, pick: 29, position: "OL", team: "NWE", division: "AFC East", college: "Chattanooga" },
  { firstName: "George", lastName: "Karlaftis", year: 2022, round: 1, pick: 30, position: "DE", team: "KAN", division: "AFC West", college: "Purdue" },
  { firstName: "Lewis", lastName: "Cine", year: 2022, round: 1, pick: 32, position: "S", team: "MIN", division: "NFC North", college: "Georgia" },
  { firstName: "Logan", lastName: "Hall", year: 2022, round: 2, pick: 33, position: "DE", team: "TAM", division: "NFC South", college: "Houston" },
  { firstName: "Christian", lastName: "Watson", year: 2022, round: 2, pick: 34, position: "WR", team: "GNB", division: "NFC North", college: "North Dakota State" },
  { firstName: "Roger", lastName: "McCreary", year: 2022, round: 2, pick: 35, position: "CB", team: "TEN", division: "AFC South", college: "Auburn" },
  { firstName: "Breece", lastName: "Hall", year: 2022, round: 2, pick: 36, position: "RB", team: "NYJ", division: "AFC East", college: "Iowa State" },
  { firstName: "Jalen", lastName: "Pitre", year: 2022, round: 2, pick: 37, position: "S", team: "HOU", division: "AFC South", college: "Baylor" },
  { firstName: "Arnold", lastName: "Ebiketie", year: 2022, round: 2, pick: 38, position: "DE", team: "ATL", division: "NFC South", college: "Penn State" },
  { firstName: "Kyler", lastName: "Gordon", year: 2022, round: 2, pick: 39, position: "CB", team: "CHI", division: "NFC North", college: "Washington" },
  { firstName: "Boye", lastName: "Mafe", year: 2022, round: 2, pick: 40, position: "DE", team: "SEA", division: "NFC West", college: "Minnesota" },
  { firstName: "Kenneth", lastName: "Walker III", year: 2022, round: 2, pick: 41, position: "RB", team: "SEA", division: "NFC West", college: "Michigan State" },
  { firstName: "Andrew", lastName: "Booth", year: 2022, round: 2, pick: 42, position: "CB", team: "MIN", division: "NFC North", college: "Clemson" },
  { firstName: "Wan'Dale", lastName: "Robinson", year: 2022, round: 2, pick: 43, position: "WR", team: "NYG", division: "NFC East", college: "Kentucky" },
  { firstName: "George", lastName: "Pickens", year: 2022, round: 2, pick: 52, position: "WR", team: "PIT", division: "AFC North", college: "Georgia" },
  { firstName: "Brian", lastName: "Robinson Jr.", year: 2022, round: 3, pick: 98, position: "RB", team: "WAS", division: "NFC East", college: "Alabama" },
  { firstName: "Dameon", lastName: "Pierce", year: 2022, round: 4, pick: 107, position: "RB", team: "HOU", division: "AFC South", college: "Florida" },
  { firstName: "Brock", lastName: "Purdy", year: 2022, round: 7, pick: 262, position: "QB", team: "SFO", division: "NFC West", college: "Iowa State" },
  { firstName: "Trevor", lastName: "Lawrence", year: 2021, round: 1, pick: 1, position: "QB", team: "JAX", division: "AFC South", college: "Clemson" },
  { firstName: "Zach", lastName: "Wilson", year: 2021, round: 1, pick: 2, position: "QB", team: "NYJ", division: "AFC East", college: "BYU" },
  { firstName: "Trey", lastName: "Lance", year: 2021, round: 1, pick: 3, position: "QB", team: "SFO", division: "NFC West", college: "North Dakota State" },
  { firstName: "Kyle", lastName: "Pitts", year: 2021, round: 1, pick: 4, position: "TE", team: "ATL", division: "NFC South", college: "Florida" },
  { firstName: "Ja'Marr", lastName: "Chase", year: 2021, round: 1, pick: 5, position: "WR", team: "CIN", division: "AFC North", college: "LSU" },
  { firstName: "Jaylen", lastName: "Waddle", year: 2021, round: 1, pick: 6, position: "WR", team: "MIA", division: "AFC East", college: "Alabama" },
  { firstName: "Penei", lastName: "Sewell", year: 2021, round: 1, pick: 7, position: "OT", team: "DET", division: "NFC North", college: "Oregon" },
  { firstName: "Jaycee", lastName: "Horn", year: 2021, round: 1, pick: 8, position: "CB", team: "CAR", division: "NFC South", college: "South Carolina" },
  { firstName: "Patrick", lastName: "Surtain II", year: 2021, round: 1, pick: 9, position: "CB", team: "DEN", division: "AFC West", college: "Alabama" },
  { firstName: "DeVonta", lastName: "Smith", year: 2021, round: 1, pick: 10, position: "WR", team: "PHI", division: "NFC East", college: "Alabama" },
  { firstName: "Justin", lastName: "Fields", year: 2021, round: 1, pick: 11, position: "QB", team: "CHI", division: "NFC North", college: "Ohio State" },
  { firstName: "Micah", lastName: "Parsons", year: 2021, round: 1, pick: 12, position: "LB", team: "DAL", division: "NFC East", college: "Penn State" },
  { firstName: "Rashawn", lastName: "Slater", year: 2021, round: 1, pick: 13, position: "OT", team: "LAC", division: "AFC West", college: "Northwestern" },
  { firstName: "Alijah", lastName: "Vera-Tucker", year: 2021, round: 1, pick: 14, position: "OL", team: "NYJ", division: "AFC East", college: "USC" },
  { firstName: "Mac", lastName: "Jones", year: 2021, round: 1, pick: 15, position: "QB", team: "NWE", division: "AFC East", college: "Alabama" },
  { firstName: "Zaven", lastName: "Collins", year: 2021, round: 1, pick: 16, position: "LB", team: "ARI", division: "NFC West", college: "Tulsa" },
  { firstName: "Alex", lastName: "Leatherwood", year: 2021, round: 1, pick: 17, position: "OL", team: "LVR", division: "AFC West", college: "Alabama" },
  { firstName: "Jaelan", lastName: "Phillips", year: 2021, round: 1, pick: 18, position: "DE", team: "MIA", division: "AFC East", college: "Miami" },
  { firstName: "Kadarius", lastName: "Toney", year: 2021, round: 1, pick: 20, position: "WR", team: "NYG", division: "NFC East", college: "Florida" },
  { firstName: "Kwity", lastName: "Paye", year: 2021, round: 1, pick: 21, position: "DE", team: "IND", division: "AFC South", college: "Michigan" },
  { firstName: "Caleb", lastName: "Farley", year: 2021, round: 1, pick: 22, position: "CB", team: "TEN", division: "AFC South", college: "Virginia Tech" },
  { firstName: "Christian", lastName: "Darrisaw", year: 2021, round: 1, pick: 23, position: "OT", team: "MIN", division: "NFC North", college: "Virginia Tech" },
  { firstName: "Najee", lastName: "Harris", year: 2021, round: 1, pick: 24, position: "RB", team: "PIT", division: "AFC North", college: "Alabama" },
  { firstName: "Travis", lastName: "Etienne", year: 2021, round: 1, pick: 25, position: "RB", team: "JAX", division: "AFC South", college: "Clemson" },
  { firstName: "Greg", lastName: "Newsome II", year: 2021, round: 1, pick: 26, position: "CB", team: "CLE", division: "AFC North", college: "Northwestern" },
  { firstName: "Rashod", lastName: "Bateman", year: 2021, round: 1, pick: 27, position: "WR", team: "BAL", division: "AFC North", college: "Minnesota" },
  { firstName: "Payton", lastName: "Turner", year: 2021, round: 1, pick: 28, position: "DE", team: "NOR", division: "NFC South", college: "Houston" },
  { firstName: "Eric", lastName: "Stokes", year: 2021, round: 1, pick: 29, position: "CB", team: "GNB", division: "NFC North", college: "Georgia" },
  { firstName: "Gregory", lastName: "Rousseau", year: 2021, round: 1, pick: 30, position: "DE", team: "BUF", division: "AFC East", college: "Miami" },
  { firstName: "Odafe", lastName: "Oweh", year: 2021, round: 1, pick: 31, position: "LB", team: "BAL", division: "AFC North", college: "Penn State" },
  { firstName: "Joe", lastName: "Tryon-Shoyinka", year: 2021, round: 1, pick: 32, position: "LB", team: "TAM", division: "NFC South", college: "Washington" },
  { firstName: "Tyson", lastName: "Campbell", year: 2021, round: 2, pick: 33, position: "CB", team: "JAX", division: "AFC South", college: "Georgia" },
  { firstName: "Elijah", lastName: "Moore", year: 2021, round: 2, pick: 34, position: "WR", team: "NYJ", division: "AFC East", college: "Ole Miss" },
  { firstName: "Javonte", lastName: "Williams", year: 2021, round: 2, pick: 35, position: "RB", team: "DEN", division: "AFC West", college: "North Carolina" },
  { firstName: "Jevon", lastName: "Holland", year: 2021, round: 2, pick: 36, position: "S", team: "MIA", division: "AFC East", college: "Oregon" },
  { firstName: "Landon", lastName: "Dickerson", year: 2021, round: 2, pick: 37, position: "OL", team: "PHI", division: "NFC East", college: "Alabama" },
  { firstName: "Christian", lastName: "Barmore", year: 2021, round: 2, pick: 38, position: "DT", team: "NWE", division: "AFC East", college: "Alabama" },
  { firstName: "Teven", lastName: "Jenkins", year: 2021, round: 2, pick: 39, position: "OL", team: "CHI", division: "NFC North", college: "Oklahoma State" },
  { firstName: "Richie", lastName: "Grant", year: 2021, round: 2, pick: 40, position: "S", team: "ATL", division: "NFC South", college: "UCF" },
  { firstName: "Liam", lastName: "Eichenberg", year: 2021, round: 2, pick: 42, position: "OL", team: "MIA", division: "AFC East", college: "Notre Dame" },
  { firstName: "Tre'Von", lastName: "Moehrig", year: 2021, round: 2, pick: 43, position: "S", team: "LVR", division: "AFC West", college: "TCU" },
  { firstName: "Amon-Ra", lastName: "St. Brown", year: 2021, round: 4, pick: 112, position: "WR", team: "DET", division: "NFC North", college: "USC" },
  { firstName: "Rhamondre", lastName: "Stevenson", year: 2021, round: 4, pick: 120, position: "RB", team: "NE", division: "AFC East", college: "Oklahoma" },
  { firstName: "Talanoa", lastName: "Hufanga", year: 2021, round: 5, pick: 180, position: "S", team: "SFO", division: "NFC West", college: "USC" },
  { firstName: "Xavier", lastName: "Worthy", year: 2024, round: 1, pick: 28, position: "WR", team: "KAN", division: "AFC West", college: "Texas" },
  { firstName: "Ladd", lastName: "McConkey", year: 2024, round: 2, pick: 34, position: "WR", team: "LAC", division: "AFC West", college: "Georgia" },
  { firstName: "Keon", lastName: "Coleman", year: 2024, round: 2, pick: 33, position: "WR", team: "BUF", division: "AFC East", college: "Florida State" },
  { firstName: "Troy", lastName: "Franklin", year: 2024, round: 4, pick: 102, position: "WR", team: "DEN", division: "AFC West", college: "Oregon" },
  { firstName: "Jaylen", lastName: "Wright", year: 2024, round: 4, pick: 120, position: "RB", team: "MIA", division: "AFC East", college: "Tennessee" },
  { firstName: "Joe", lastName: "Burrow", year: 2020, round: 1, pick: 1, position: "QB", team: "CIN", division: "AFC North", college: "LSU" },
  { firstName: "Chase", lastName: "Young", year: 2020, round: 1, pick: 2, position: "DE", team: "WAS", division: "NFC East", college: "Ohio State" },
  { firstName: "Jeff", lastName: "Okudah", year: 2020, round: 1, pick: 3, position: "CB", team: "DET", division: "NFC North", college: "Ohio State" },
  { firstName: "Andrew", lastName: "Thomas", year: 2020, round: 1, pick: 4, position: "OT", team: "NYG", division: "NFC East", college: "Georgia" },
  { firstName: "Tua", lastName: "Tagovailoa", year: 2020, round: 1, pick: 5, position: "QB", team: "MIA", division: "AFC East", college: "Alabama" },
  { firstName: "Justin", lastName: "Herbert", year: 2020, round: 1, pick: 6, position: "QB", team: "LAC", division: "AFC West", college: "Oregon" },
  { firstName: "Derrick", lastName: "Brown", year: 2020, round: 1, pick: 7, position: "DT", team: "CAR", division: "NFC South", college: "Auburn" },
  { firstName: "Isaiah", lastName: "Simmons", year: 2020, round: 1, pick: 8, position: "LB", team: "ARI", division: "NFC West", college: "Clemson" },
  { firstName: "C.J.", lastName: "Henderson", year: 2020, round: 1, pick: 9, position: "CB", team: "JAX", division: "AFC South", college: "Florida" },
  { firstName: "Jedrick", lastName: "Wills Jr.", year: 2020, round: 1, pick: 10, position: "OT", team: "CLE", division: "AFC North", college: "Alabama" },
  { firstName: "Mekhi", lastName: "Becton", year: 2020, round: 1, pick: 11, position: "OT", team: "NYJ", division: "AFC East", college: "Louisville" },
  { firstName: "Henry", lastName: "Ruggs III", year: 2020, round: 1, pick: 12, position: "WR", team: "LVR", division: "AFC West", college: "Alabama" },
  { firstName: "Tristan", lastName: "Wirfs", year: 2020, round: 1, pick: 13, position: "OT", team: "TAM", division: "NFC South", college: "Iowa" },
  { firstName: "Javon", lastName: "Kinlaw", year: 2020, round: 1, pick: 14, position: "DT", team: "SFO", division: "NFC West", college: "South Carolina" },
  { firstName: "Jerry", lastName: "Jeudy", year: 2020, round: 1, pick: 15, position: "WR", team: "DEN", division: "AFC West", college: "Alabama" },
  { firstName: "A.J.", lastName: "Terrell", year: 2020, round: 1, pick: 16, position: "CB", team: "ATL", division: "NFC South", college: "Clemson" },
  { firstName: "CeeDee", lastName: "Lamb", year: 2020, round: 1, pick: 17, position: "WR", team: "DAL", division: "NFC East", college: "Oklahoma" },
  { firstName: "Damon", lastName: "Arnette", year: 2020, round: 1, pick: 19, position: "CB", team: "LVR", division: "AFC West", college: "Ohio State" },
  { firstName: "K'Lavon", lastName: "Chaisson", year: 2020, round: 1, pick: 20, position: "LB", team: "JAX", division: "AFC South", college: "LSU" },
  { firstName: "Jalen", lastName: "Reagor", year: 2020, round: 1, pick: 21, position: "WR", team: "PHI", division: "NFC East", college: "TCU" },
  { firstName: "Justin", lastName: "Jefferson", year: 2020, round: 1, pick: 22, position: "WR", team: "MIN", division: "NFC North", college: "LSU" },
  { firstName: "Kenneth", lastName: "Murray", year: 2020, round: 1, pick: 23, position: "LB", team: "LAC", division: "AFC West", college: "Oklahoma" },
  { firstName: "Brandon", lastName: "Aiyuk", year: 2020, round: 1, pick: 25, position: "WR", team: "SFO", division: "NFC West", college: "Arizona State" },
  { firstName: "Jordan", lastName: "Love", year: 2020, round: 1, pick: 26, position: "QB", team: "GNB", division: "NFC North", college: "Utah State" },
  { firstName: "Patrick", lastName: "Queen", year: 2020, round: 1, pick: 28, position: "LB", team: "BAL", division: "AFC North", college: "LSU" },
  { firstName: "Clyde", lastName: "Edwards-Helaire", year: 2020, round: 1, pick: 32, position: "RB", team: "KAN", division: "AFC West", college: "LSU" },
  { firstName: "Tee", lastName: "Higgins", year: 2020, round: 2, pick: 33, position: "WR", team: "CIN", division: "AFC North", college: "Clemson" },
  { firstName: "Michael", lastName: "Pittman Jr.", year: 2020, round: 2, pick: 34, position: "WR", team: "IND", division: "AFC South", college: "USC" },
  { firstName: "D'Andre", lastName: "Swift", year: 2020, round: 2, pick: 35, position: "RB", team: "DET", division: "NFC North", college: "Georgia" },
  { firstName: "Xavier", lastName: "McKinney", year: 2020, round: 2, pick: 36, position: "S", team: "NYG", division: "NFC East", college: "Alabama" },
  { firstName: "Kyle", lastName: "Dugger", year: 2020, round: 2, pick: 37, position: "S", team: "NWE", division: "AFC East", college: "Lenoir-Rhyne" },
  { firstName: "Robert", lastName: "Hunt", year: 2020, round: 2, pick: 39, position: "OL", team: "MIA", division: "AFC East", college: "Louisiana" },
  { firstName: "Jalen", lastName: "Hurts", year: 2020, round: 2, pick: 53, position: "QB", team: "PHI", division: "NFC East", college: "Oklahoma" },
  { firstName: "Jonathan", lastName: "Taylor", year: 2020, round: 2, pick: 41, position: "RB", team: "IND", division: "AFC South", college: "Wisconsin" },
  { firstName: "Trevon", lastName: "Diggs", year: 2020, round: 2, pick: 51, position: "CB", team: "DAL", division: "NFC East", college: "Alabama" },
  { firstName: "Antoine", lastName: "Winfield Jr.", year: 2020, round: 2, pick: 45, position: "S", team: "TAM", division: "NFC South", college: "Minnesota" },
  { firstName: "Jeremy", lastName: "Chinn", year: 2020, round: 2, pick: 64, position: "S", team: "CAR", division: "NFC South", college: "Southern Illinois" },
  { firstName: "Gabe", lastName: "Davis", year: 2020, round: 4, pick: 128, position: "WR", team: "BUF", division: "AFC East", college: "UCF" },
  { firstName: "Kyler", lastName: "Murray", year: 2019, round: 1, pick: 1, position: "QB", team: "ARI", division: "NFC West", college: "Oklahoma" },
{ firstName: "Nick", lastName: "Bosa", year: 2019, round: 1, pick: 2, position: "DE", team: "SFO", division: "NFC West", college: "Ohio State" },
{ firstName: "Quinnen", lastName: "Williams", year: 2019, round: 1, pick: 3, position: "DT", team: "NYJ", division: "AFC East", college: "Alabama" },
{ firstName: "Clelin", lastName: "Ferrell", year: 2019, round: 1, pick: 4, position: "DE", team: "LVR", division: "AFC West", college: "Clemson" },
{ firstName: "Devin", lastName: "White", year: 2019, round: 1, pick: 5, position: "LB", team: "TAM", division: "NFC South", college: "LSU" },
{ firstName: "Daniel", lastName: "Jones", year: 2019, round: 1, pick: 6, position: "QB", team: "NYG", division: "NFC East", college: "Duke" },
{ firstName: "Josh", lastName: "Allen", year: 2019, round: 1, pick: 7, position: "DE", team: "JAX", division: "AFC South", college: "Kentucky" },
{ firstName: "T.J.", lastName: "Hockenson", year: 2019, round: 1, pick: 8, position: "TE", team: "DET", division: "NFC North", college: "Iowa" },
{ firstName: "Ed", lastName: "Oliver", year: 2019, round: 1, pick: 9, position: "DT", team: "BUF", division: "AFC East", college: "Houston" },
{ firstName: "Devin", lastName: "Bush Jr.", year: 2019, round: 1, pick: 10, position: "LB", team: "PIT", division: "AFC North", college: "Michigan" },
{ firstName: "Jonah", lastName: "Williams", year: 2019, round: 1, pick: 11, position: "OT", team: "CIN", division: "AFC North", college: "Alabama" },
{ firstName: "Rashan", lastName: "Gary", year: 2019, round: 1, pick: 12, position: "LB", team: "GNB", division: "NFC North", college: "Michigan" },
{ firstName: "Christian", lastName: "Wilkins", year: 2019, round: 1, pick: 13, position: "DT", team: "MIA", division: "AFC East", college: "Clemson" },
{ firstName: "Chris", lastName: "Lindstrom", year: 2019, round: 1, pick: 14, position: "OG", team: "ATL", division: "NFC South", college: "Boston College" },
{ firstName: "Dwayne", lastName: "Haskins", year: 2019, round: 1, pick: 15, position: "QB", team: "WAS", division: "NFC East", college: "Ohio State" },
{ firstName: "Brian", lastName: "Burns", year: 2019, round: 1, pick: 16, position: "DE", team: "CAR", division: "NFC South", college: "Florida State" },
{ firstName: "Dexter", lastName: "Lawrence", year: 2019, round: 1, pick: 17, position: "DT", team: "NYG", division: "NFC East", college: "Clemson" },
{ firstName: "Jeffery", lastName: "Simmons", year: 2019, round: 1, pick: 19, position: "DT", team: "TEN", division: "AFC South", college: "Mississippi State" },
{ firstName: "Noah", lastName: "Fant", year: 2019, round: 1, pick: 20, position: "TE", team: "DEN", division: "AFC West", college: "Iowa" },
{ firstName: "Darnell", lastName: "Savage Jr.", year: 2019, round: 1, pick: 21, position: "S", team: "GNB", division: "NFC North", college: "Maryland" },
{ firstName: "Andre", lastName: "Dillard", year: 2019, round: 1, pick: 22, position: "OT", team: "PHI", division: "NFC East", college: "Washington State" },
{ firstName: "Josh", lastName: "Jacobs", year: 2019, round: 1, pick: 24, position: "RB", team: "LVR", division: "AFC West", college: "Alabama" },
{ firstName: "Marquise", lastName: "Brown", year: 2019, round: 1, pick: 25, position: "WR", team: "BAL", division: "AFC North", college: "Oklahoma" },
{ firstName: "Montez", lastName: "Sweat", year: 2019, round: 1, pick: 26, position: "DE", team: "WAS", division: "NFC East", college: "Mississippi State" },
{ firstName: "L.J.", lastName: "Collier", year: 2019, round: 1, pick: 29, position: "DE", team: "SEA", division: "NFC West", college: "TCU" },
{ firstName: "Deebo", lastName: "Samuel", year: 2019, round: 2, pick: 36, position: "WR", team: "SFO", division: "NFC West", college: "South Carolina" },
{ firstName: "Drew", lastName: "Lock", year: 2019, round: 2, pick: 42, position: "QB", team: "DEN", division: "AFC West", college: "Missouri" },
{ firstName: "A.J.", lastName: "Brown", year: 2019, round: 2, pick: 51, position: "WR", team: "TEN", division: "AFC South", college: "Ole Miss" },
{ firstName: "D.K.", lastName: "Metcalf", year: 2019, round: 2, pick: 64, position: "WR", team: "SEA", division: "NFC West", college: "Ole Miss" },
{ firstName: "Terry", lastName: "McLaurin", year: 2019, round: 3, pick: 76, position: "WR", team: "WAS", division: "NFC East", college: "Ohio State" },
{ firstName: "David", lastName: "Montgomery", year: 2019, round: 3, pick: 73, position: "RB", team: "CHI", division: "NFC North", college: "Iowa State" },
{ firstName: "Diontae", lastName: "Johnson", year: 2019, round: 3, pick: 66, position: "WR", team: "PIT", division: "AFC North", college: "Toledo" },
{ firstName: "Maxx", lastName: "Crosby", year: 2019, round: 4, pick: 106, position: "DE", team: "LVR", division: "AFC West", college: "Eastern Michigan" },
{ firstName: "Hunter", lastName: "Renfrow", year: 2019, round: 5, pick: 149, position: "WR", team: "LVR", division: "AFC West", college: "Clemson" },
{ firstName: "Gardner", lastName: "Minshew", year: 2019, round: 6, pick: 178, position: "QB", team: "JAX", division: "AFC South", college: "Washington State" },
{ firstName: "Tony", lastName: "Pollard", year: 2019, round: 4, pick: 128, position: "RB", team: "DAL", division: "NFC East", college: "Memphis" },
{ firstName: "Chauncey", lastName: "Gardner-Johnson", year: 2019, round: 4, pick: 105, position: "DB", team: "NOR", division: "NFC South", college: "Florida" },
  { firstName: "Baker", lastName: "Mayfield", year: 2018, round: 1, pick: 1, position: "QB", team: "CLE", division: "AFC North", college: "Oklahoma" },
  { firstName: "Saquon", lastName: "Barkley", year: 2018, round: 1, pick: 2, position: "RB", team: "NYG", division: "NFC East", college: "Penn State" },
  { firstName: "Sam", lastName: "Darnold", year: 2018, round: 1, pick: 3, position: "QB", team: "NYJ", division: "AFC East", college: "USC" },
  { firstName: "Denzel", lastName: "Ward", year: 2018, round: 1, pick: 4, position: "CB", team: "CLE", division: "AFC North", college: "Ohio State" },
  { firstName: "Bradley", lastName: "Chubb", year: 2018, round: 1, pick: 5, position: "LB", team: "DEN", division: "AFC West", college: "NC State" },
  { firstName: "Josh", lastName: "Allen", year: 2018, round: 1, pick: 7, position: "QB", team: "BUF", division: "AFC East", college: "Wyoming" },
  { firstName: "Roquan", lastName: "Smith", year: 2018, round: 1, pick: 8, position: "LB", team: "CHI", division: "NFC North", college: "Georgia" },
  { firstName: "Minkah", lastName: "Fitzpatrick", year: 2018, round: 1, pick: 11, position: "S", team: "MIA", division: "AFC East", college: "Alabama" },
  { firstName: "Vita", lastName: "Vea", year: 2018, round: 1, pick: 12, position: "DT", team: "TAM", division: "NFC South", college: "Washington" },
  { firstName: "Derwin", lastName: "James", year: 2018, round: 1, pick: 17, position: "S", team: "LAC", division: "AFC West", college: "Florida State" },
  { firstName: "Jaire", lastName: "Alexander", year: 2018, round: 1, pick: 18, position: "CB", team: "GNB", division: "NFC North", college: "Louisville" },
  { firstName: "Leighton", lastName: "Vander Esch", year: 2018, round: 1, pick: 19, position: "LB", team: "DAL", division: "NFC East", college: "Boise State" },
  { firstName: "Calvin", lastName: "Ridley", year: 2018, round: 1, pick: 26, position: "WR", team: "ATL", division: "NFC South", college: "Alabama" },
  { firstName: "Lamar", lastName: "Jackson", year: 2018, round: 1, pick: 32, position: "QB", team: "BAL", division: "AFC North", college: "Louisville" },
  { firstName: "Nick", lastName: "Chubb", year: 2018, round: 2, pick: 35, position: "RB", team: "CLE", division: "AFC North", college: "Georgia" },
  { firstName: "Shaquille", lastName: "Leonard", year: 2018, round: 2, pick: 36, position: "LB", team: "IND", division: "AFC South", college: "South Carolina State" },
  { firstName: "Courtland", lastName: "Sutton", year: 2018, round: 2, pick: 40, position: "WR", team: "DEN", division: "AFC West", college: "SMU" },
  { firstName: "Harold", lastName: "Landry", year: 2018, round: 2, pick: 41, position: "LB", team: "TEN", division: "AFC South", college: "Boston College" },
  { firstName: "Mike", lastName: "Gesicki", year: 2018, round: 2, pick: 42, position: "TE", team: "MIA", division: "AFC East", college: "Penn State" },
  { firstName: "Mark", lastName: "Andrews", year: 2018, round: 3, pick: 86, position: "TE", team: "BAL", division: "AFC North", college: "Oklahoma" },
  { firstName: "Orlando", lastName: "Brown Jr.", year: 2018, round: 3, pick: 83, position: "OT", team: "BAL", division: "AFC North", college: "Oklahoma" },
  { firstName: "Fred", lastName: "Warner", year: 2018, round: 3, pick: 70, position: "LB", team: "SFO", division: "NFC West", college: "BYU" },
  { firstName: "Jessie", lastName: "Bates", year: 2018, round: 2, pick: 54, position: "S", team: "CIN", division: "AFC North", college: "Wake Forest" },
  { firstName: "Dallas", lastName: "Goedert", year: 2018, round: 2, pick: 49, position: "TE", team: "PHI", division: "NFC East", college: "South Dakota State" },
  { firstName: "Myles", lastName: "Garrett", year: 2017, round: 1, pick: 1, position: "DE", team: "CLE", division: "AFC North", college: "Texas A&M" },
  { firstName: "Mitchell", lastName: "Trubisky", year: 2017, round: 1, pick: 2, position: "QB", team: "CHI", division: "NFC North", college: "North Carolina" },
  { firstName: "Solomon", lastName: "Thomas", year: 2017, round: 1, pick: 3, position: "DL", team: "SF", division: "NFC West", college: "Stanford" },
  { firstName: "Leonard", lastName: "Fournette", year: 2017, round: 1, pick: 4, position: "RB", team: "JAX", division: "AFC South", college: "LSU" },
  { firstName: "Corey", lastName: "Davis", year: 2017, round: 1, pick: 5, position: "WR", team: "TEN", division: "AFC South", college: "Western Michigan" },
  { firstName: "Jamal", lastName: "Adams", year: 2017, round: 1, pick: 6, position: "S", team: "NYJ", division: "AFC East", college: "LSU" },
  { firstName: "Mike", lastName: "Williams", year: 2017, round: 1, pick: 7, position: "WR", team: "LAC", division: "AFC West", college: "Clemson" },
  { firstName: "Christian", lastName: "McCaffrey", year: 2017, round: 1, pick: 8, position: "RB", team: "CAR", division: "NFC South", college: "Stanford" },
  { firstName: "John", lastName: "Ross", year: 2017, round: 1, pick: 9, position: "WR", team: "CIN", division: "AFC North", college: "Washington" },
  { firstName: "Patrick", lastName: "Mahomes", year: 2017, round: 1, pick: 10, position: "QB", team: "KC", division: "AFC West", college: "Texas Tech" },
  { firstName: "Marshon", lastName: "Lattimore", year: 2017, round: 1, pick: 11, position: "CB", team: "NO", division: "NFC South", college: "Ohio State" },
  { firstName: "Deshaun", lastName: "Watson", year: 2017, round: 1, pick: 12, position: "QB", team: "HOU", division: "AFC South", college: "Clemson" },
  { firstName: "Haason", lastName: "Reddick", year: 2017, round: 1, pick: 13, position: "LB", team: "ARI", division: "NFC West", college: "Temple" },
  { firstName: "Derek", lastName: "Barnett", year: 2017, round: 1, pick: 14, position: "DE", team: "PHI", division: "NFC East", college: "Tennessee" },
  { firstName: "Malik", lastName: "Hooker", year: 2017, round: 1, pick: 15, position: "S", team: "IND", division: "AFC South", college: "Ohio State" },
  { firstName: "Marlon", lastName: "Humphrey", year: 2017, round: 1, pick: 16, position: "CB", team: "BAL", division: "AFC North", college: "Alabama" },
  { firstName: "Jonathan", lastName: "Allen", year: 2017, round: 1, pick: 17, position: "DL", team: "WAS", division: "NFC East", college: "Alabama" },
  { firstName: "Adoree’", lastName: "Jackson", year: 2017, round: 1, pick: 18, position: "CB", team: "TEN", division: "AFC South", college: "USC" },
  { firstName: "O.J.", lastName: "Howard", year: 2017, round: 1, pick: 19, position: "TE", team: "TB", division: "NFC South", college: "Alabama" },
  { firstName: "Garett", lastName: "Bolles", year: 2017, round: 1, pick: 20, position: "OT", team: "DEN", division: "AFC West", college: "Utah" },
  { firstName: "Jarrad", lastName: "Davis", year: 2017, round: 1, pick: 21, position: "LB", team: "DET", division: "NFC North", college: "Florida" },
  { firstName: "Charles", lastName: "Harris", year: 2017, round: 1, pick: 22, position: "LB", team: "MIA", division: "AFC East", college: "Missouri" },
  { firstName: "Evan", lastName: "Engram", year: 2017, round: 1, pick: 23, position: "TE", team: "NYG", division: "NFC East", college: "Ole Miss" },
  { firstName: "Gareon", lastName: "Conley", year: 2017, round: 1, pick: 24, position: "CB", team: "OAK", division: "AFC West", college: "Ohio State" },
  { firstName: "Jabrill", lastName: "Peppers", year: 2017, round: 1, pick: 25, position: "S", team: "CLE", division: "AFC North", college: "Michigan" },
  { firstName: "Takkarist", lastName: "McKinley", year: 2017, round: 1, pick: 26, position: "DE", team: "ATL", division: "NFC South", college: "UCLA" },
  { firstName: "Tre’Davious", lastName: "White", year: 2017, round: 1, pick: 27, position: "CB", team: "BUF", division: "AFC East", college: "LSU" },
  { firstName: "Taco", lastName: "Charlton", year: 2017, round: 1, pick: 28, position: "DE", team: "DAL", division: "NFC East", college: "Michigan" },
  { firstName: "David", lastName: "Njoku", year: 2017, round: 1, pick: 29, position: "TE", team: "CLE", division: "AFC North", college: "Miami (FL)" },
  { firstName: "T.J.", lastName: "Watt", year: 2017, round: 1, pick: 30, position: "LB", team: "PIT", division: "AFC North", college: "Wisconsin" },
  { firstName: "Reuben", lastName: "Foster", year: 2017, round: 1, pick: 31, position: "LB", team: "SF", division: "NFC West", college: "Alabama" },
  { firstName: "Ryan", lastName: "Ramczyk", year: 2017, round: 1, pick: 32, position: "OT", team: "NO", division: "NFC South", college: "Wisconsin" },
  { firstName: "Kevin", lastName: "King", year: 2017, round: 2, pick: 33, position: "CB", team: "GB", division: "NFC North", college: "Washington" },
  { firstName: "Cam", lastName: "Robinson", year: 2017, round: 2, pick: 34, position: "OT", team: "JAX", division: "AFC South", college: "Alabama" },
  { firstName: "Malik", lastName: "McDowell", year: 2017, round: 2, pick: 35, position: "DT", team: "SEA", division: "NFC West", college: "Michigan State" },
  { firstName: "Budda", lastName: "Baker", year: 2017, round: 2, pick: 36, position: "S", team: "ARI", division: "NFC West", college: "Washington" },
  { firstName: "Zay", lastName: "Jones", year: 2017, round: 2, pick: 37, position: "WR", team: "BUF", division: "AFC East", college: "East Carolina" },
  { firstName: "Marcus", lastName: "Maye", year: 2017, round: 2, pick: 39, position: "S", team: "NYJ", division: "AFC East", college: "Florida" },
  { firstName: "Curtis", lastName: "Samuel", year: 2017, round: 2, pick: 40, position: "WR", team: "CAR", division: "NFC South", college: "Ohio State" },
  { firstName: "Dalvin", lastName: "Cook", year: 2017, round: 2, pick: 41, position: "RB", team: "MIN", division: "NFC North", college: "Florida State" },
  { firstName: "JuJu", lastName: "Smith-Schuster", year: 2017, round: 2, pick: 62, position: "WR", team: "PIT", division: "AFC North", college: "USC" },
  { firstName: "Alvin", lastName: "Kamara", year: 2017, round: 3, pick: 67, position: "RB", team: "NO", division: "NFC South", college: "Tennessee" },
  { firstName: "Cooper", lastName: "Kupp", year: 2017, round: 3, pick: 69, position: "WR", team: "LAR", division: "NFC West", college: "Eastern Washington" },
  { firstName: "Chris", lastName: "Godwin", year: 2017, round: 3, pick: 84, position: "WR", team: "TB", division: "NFC South", college: "Penn State" },
  { firstName: "Kareem", lastName: "Hunt", year: 2017, round: 3, pick: 86, position: "RB", team: "KC", division: "AFC West", college: "Toledo" },
  { firstName: "George", lastName: "Kittle", year: 2017, round: 5, pick: 146, position: "TE", team: "SF", division: "NFC West", college: "Iowa" },
  { firstName: "Aaron", lastName: "Jones", year: 2017, round: 5, pick: 182, position: "RB", team: "GB", division: "NFC North", college: "UTEP" },
];