type Player = {
  firstName: string;
  lastName: string;
  jerseyNumber: number;
  teamPrimaryColor: string;
  teamSecondaryColor: string;
};

export const players: Player[] = [
 //Buffalo Bills
 { firstName: "Keon", lastName: "Coleman", jerseyNumber: 0, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { firstName: "Josh", lastName: "Palmer", jerseyNumber: 5, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { firstName: "Khalil", lastName: "Shakir", jerseyNumber: 10, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { firstName: "Dion", lastName: "Dawkins", jerseyNumber: 73, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { firstName: "Ryan", lastName: "Edwards", jerseyNumber: 76, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { firstName: "Connor", lastName: "McGovern", jerseyNumber: 66, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { firstName: "O'Cyrus", lastName: "Torrence", jerseyNumber: 64, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { firstName: "Spencer", lastName: "Brown", jerseyNumber: 79, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { firstName: "Dalton", lastName: "Kincaid", jerseyNumber: 86, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { firstName: "Josh", lastName: "Allen", jerseyNumber: 17, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { firstName: "James", lastName: "Cook", jerseyNumber: 4, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { firstName: "Reggie", lastName: "Gilliam", jerseyNumber: 41, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { firstName: "Gregory", lastName: "Rousseau", jerseyNumber: 50, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { firstName: "DaQuan", lastName: "Jones", jerseyNumber: 92, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { firstName: "Ed", lastName: "Oliver", jerseyNumber: 91, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { firstName: "Joey", lastName: "Bosa", jerseyNumber: 97, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { firstName: "Matt", lastName: "Milano", jerseyNumber: 58, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { firstName: "Terrel", lastName: "Bernard", jerseyNumber: 43, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { firstName: "Christian", lastName: "Benford", jerseyNumber: 47, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },
  { firstName: "Cole", lastName: "Bishop", jerseyNumber: 32, teamPrimaryColor: "#00338D", teamSecondaryColor: "#FFFFFF" },

  // Miami Dolphins
  { firstName: "Jaylen", lastName: "Waddle", jerseyNumber: 17, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Tyreek", lastName: "Hill", jerseyNumber: 10, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Malik", lastName: "Washington", jerseyNumber: 6, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Patrick", lastName: "Paul", jerseyNumber: 52, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Lester", lastName: "Daniels", jerseyNumber: 78, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Aaron", lastName: "Brewer", jerseyNumber: 55, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Mahe", lastName: "Savaiinaea", jerseyNumber: 72, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Austin", lastName: "Jackson", jerseyNumber: 73, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Darren", lastName: "Waller", jerseyNumber: 83, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Tua", lastName: "Tagovailoa", jerseyNumber: 1, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "De'Von", lastName: "Achane", jerseyNumber: 28, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Alec", lastName: "Ingold", jerseyNumber: 30, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Emmanuel", lastName: "Grant", jerseyNumber: 90, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Brandon", lastName: "Jones", jerseyNumber: 95, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Zach", lastName: "Sieler", jerseyNumber: 92, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Jaelan", lastName: "Phillips", jerseyNumber: 15, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Cam", lastName: "Brooks", jerseyNumber: 20, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Dorian", lastName: "Dodson", jerseyNumber: 11, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Bradley", lastName: "Chubb", jerseyNumber: 2, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Cam", lastName: "Duck", jerseyNumber: 36, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Obi", lastName: "Melifonwu", jerseyNumber: 9, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Minkah", lastName: "Fitzpatrick", jerseyNumber: 29, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Xavien", lastName: "Jones", jerseyNumber: 23, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },
  { firstName: "Taron", lastName: "Hilton", jerseyNumber: 38, teamPrimaryColor: "#008e97", teamSecondaryColor: "#ffffff" },

  // New England Patriots (Primary: #002244, Secondary: #C60C30)
{ firstName: "Stephon", lastName: "Diggs", jerseyNumber: 8, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Mack", lastName: "Hollins", jerseyNumber: 13, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Demario", lastName: "Douglas", jerseyNumber: 3, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Caleb", lastName: "Campbell", jerseyNumber: 66, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Chuma", lastName: "Wilson", jerseyNumber: 58, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Garrett", lastName: "Bradbury", jerseyNumber: 65, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Michael", lastName: "Onwenu", jerseyNumber: 71, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Morgan", lastName: "Moses", jerseyNumber: 76, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Hunter", lastName: "Henry", jerseyNumber: 85, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Drake", lastName: "Maye", jerseyNumber: 10, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Rhamondre", lastName: "Stevenson", jerseyNumber: 38, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Deatrich", lastName: "Wise", jerseyNumber: 99, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Christian", lastName: "Barmore", jerseyNumber: 90, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Davon", lastName: "Williams", jerseyNumber: 97, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Harold", lastName: "Landry", jerseyNumber: 2, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Kaden", lastName: "Elliss", jerseyNumber: 53, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Robert", lastName: "Spillane", jerseyNumber: 14, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Anfernee", lastName: "Jennings", jerseyNumber: 33, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Carlton", lastName: "Davis", jerseyNumber: 7, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Kyle", lastName: "Dugger", jerseyNumber: 23, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Jabrill", lastName: "Peppers", jerseyNumber: 5, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Christian", lastName: "Gonzalez", jerseyNumber: 0, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },
{ firstName: "Marcus", lastName: "Jones", jerseyNumber: 25, teamPrimaryColor: "#002244", teamSecondaryColor: "#C60C30" },

  // New York Jets
{ firstName: "Garrett", lastName: "Wilson", jerseyNumber: 5, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Craig", lastName: "Reynolds", jerseyNumber: 83, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Tyron", lastName: "Johnson", jerseyNumber: 16, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Olu", lastName: "Fashanu", jerseyNumber: 74, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Christian", lastName: "Simpson", jerseyNumber: 76, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Joe", lastName: "Tippmann", jerseyNumber: 66, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Alijah", lastName: "Vera-Tucker", jerseyNumber: 75, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Max", lastName: "Membou", jerseyNumber: 70, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Malik", lastName: "Taylor", jerseyNumber: 85, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Justin", lastName: "Fields", jerseyNumber: 7, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Breece", lastName: "Hall", jerseyNumber: 20, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Nick", lastName: "Beck", jerseyNumber: 47, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Will", lastName: "McDonald IV", jerseyNumber: 9, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Byron", lastName: "Cowart", jerseyNumber: 93, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Quinnen", lastName: "Williams", jerseyNumber: 95, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Jermaine", lastName: "Johnson", jerseyNumber: 11, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Quincy", lastName: "Williams", jerseyNumber: 56, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Jamien", lastName: "Sherwood", jerseyNumber: 44, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Sauce", lastName: "Gardner", jerseyNumber: 1, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Trey", lastName: "Moore", jerseyNumber: 27, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Andre", lastName: "Cisco", jerseyNumber: 8, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Brandon", lastName: "Stephens", jerseyNumber: 21, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },
{ firstName: "Michael", lastName: "Carter II", jerseyNumber: 30, teamPrimaryColor: "#125740", teamSecondaryColor: "#ffffff" },

   // Dallas Cowboys
{ firstName: "George", lastName: "Pickens", jerseyNumber: 3, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "Jalen", lastName: "Tolbert", jerseyNumber: 1, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "CeeDee", lastName: "Lamb", jerseyNumber: 88, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "Brandon", lastName: "Guyton", jerseyNumber: 60, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "Tyron", lastName: "Smith", jerseyNumber: 73, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "Cooper", lastName: "Beebe", jerseyNumber: 56, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "Brock", lastName: "Booker", jerseyNumber: 52, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "Terence", lastName: "Steele", jerseyNumber: 78, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "Jake", lastName: "Ferguson", jerseyNumber: 87, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "Dak", lastName: "Prescott", jerseyNumber: 4, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "Rico", lastName: "Williams", jerseyNumber: 33, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "Hunter", lastName: "Luepke", jerseyNumber: 40, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "Dante", lastName: "Fowler", jerseyNumber: 13, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "Tyler", lastName: "Smith", jerseyNumber: 58, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "Osa", lastName: "Odighizuwa", jerseyNumber: 97, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "Micah", lastName: "Parsons", jerseyNumber: 11, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "DeMarvion", lastName: "Overshown", jerseyNumber: 0, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "Eric", lastName: "Murray", jerseyNumber: 59, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "Trevon", lastName: "Diggs", jerseyNumber: 7, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "Malik", lastName: "Hooker", jerseyNumber: 28, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "Donovan", lastName: "Wilson", jerseyNumber: 6, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "Kaiir", lastName: "Elam", jerseyNumber: 20, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },
{ firstName: "DaRon", lastName: "Bland", jerseyNumber: 26, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFFFFF" },

// New York Giants
{ firstName: "Malik", lastName: "Nabers", jerseyNumber: 1, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "Darius", lastName: "Slayton", jerseyNumber: 18, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "Wan'Dale", lastName: "Robinson", jerseyNumber: 17, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "Andrew", lastName: "Thomas", jerseyNumber: 78, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "Jon", lastName: "Runyan", jerseyNumber: 76, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "John Michael", lastName: "Schmitz Jr.", jerseyNumber: 61, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "Greg", lastName: "Van Roten", jerseyNumber: 74, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "Jermaine", lastName: "Eluemunor", jerseyNumber: 72, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "Collin", lastName: "Johnson", jerseyNumber: 84, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "Jayden", lastName: "Wilson", jerseyNumber: 3, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "Tyrone", lastName: "Tracy Jr.", jerseyNumber: 29, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "Roy", lastName: "Robertson-Harris", jerseyNumber: 95, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "Dexter", lastName: "Lawrence II", jerseyNumber: 97, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "Rakeem", lastName: "Núñez-Roches", jerseyNumber: 93, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "Brian", lastName: "Burns", jerseyNumber: 0, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "Bobby", lastName: "Okereke", jerseyNumber: 58, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "Micah", lastName: "McFadden", jerseyNumber: 41, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "Dyontae", lastName: "Carter", jerseyNumber: 51, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "Paulson", lastName: "Adebo", jerseyNumber: 21, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "Tyler", lastName: "Nubin", jerseyNumber: 27, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "Jevon", lastName: "Holland", jerseyNumber: 8, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "Deonte", lastName: "Banks", jerseyNumber: 2, teamPrimaryColor: "blue", teamSecondaryColor: "white" },
{ firstName: "Darnay", lastName: "Phillips", jerseyNumber: 22, teamPrimaryColor: "blue", teamSecondaryColor: "white" },

// Philadelphia Eagles
{ firstName: "A.J.", lastName: "Brown", jerseyNumber: 11, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Jahan", lastName: "Dotson", jerseyNumber: 2, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "DeVonta", lastName: "Smith", jerseyNumber: 6, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Jordan", lastName: "Mailata", jerseyNumber: 68, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Landon", lastName: "Dickerson", jerseyNumber: 69, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Cam", lastName: "Jurgens", jerseyNumber: 51, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Tyler", lastName: "Steen", jerseyNumber: 56, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Lane", lastName: "Johnson", jerseyNumber: 65, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Dallas", lastName: "Goedert", jerseyNumber: 88, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Jalen", lastName: "Hurts", jerseyNumber: 1, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Saquon", lastName: "Barkley", jerseyNumber: 26, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Ben", lastName: "VanSumeren", jerseyNumber: 43, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Moro", lastName: "Ojomo", jerseyNumber: 97, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Jordan", lastName: "Davis", jerseyNumber: 90, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Jalen", lastName: "Carter", jerseyNumber: 98, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Nolan", lastName: "Smith Jr.", jerseyNumber: 3, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Zack", lastName: "Baun", jerseyNumber: 53, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Nakobe", lastName: "Dean", jerseyNumber: 17, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Oren", lastName: "Hunt", jerseyNumber: 58, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Kelee", lastName: "Ringo", jerseyNumber: 7, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Sydney", lastName: "Brown", jerseyNumber: 21, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Reed", lastName: "Blankenship", jerseyNumber: 32, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Kelee", lastName: "Mitchell", jerseyNumber: 27, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },
{ firstName: "Cooper", lastName: "DeJean", jerseyNumber: 33, teamPrimaryColor: "midnight green", teamSecondaryColor: "white" },

//commanders
{ firstName: "Terry", lastName: "McLaurin", jerseyNumber: 17, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ firstName: "Dyami", lastName: "Brown", jerseyNumber: 85, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ firstName: "Curtis", lastName: "Samuel", jerseyNumber: 1, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ firstName: "Laremy", lastName: "Tunsil", jerseyNumber: 78, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ firstName: "Cornelius", lastName: "Coleman", jerseyNumber: 74, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ firstName: "Tyler", lastName: "Biadasz", jerseyNumber: 63, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ firstName: "Sam", lastName: "Cosmi", jerseyNumber: 76, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ firstName: "Andrew", lastName: "Wylie", jerseyNumber: 71, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ firstName: "Zach", lastName: "Ertz", jerseyNumber: 86, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ firstName: "Jayden", lastName: "Daniels", jerseyNumber: 5, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ firstName: "Brian", lastName: "Robinson Jr.", jerseyNumber: 8, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ firstName: "Dorance", lastName: "Armstrong", jerseyNumber: 92, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ firstName: "Daron", lastName: "Payne", jerseyNumber: 94, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ firstName: "Javon", lastName: "Kinlaw", jerseyNumber: 52, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ firstName: "Braden", lastName: "Miller", jerseyNumber: 24, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ firstName: "Frankie", lastName: "Luvu", jerseyNumber: 4, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ firstName: "Bobby", lastName: "Wagner", jerseyNumber: 54, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ firstName: "Adrian", lastName: "Amos", jerseyNumber: 23, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ firstName: "D'Angelo", lastName: "Harris", jerseyNumber: 3, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ firstName: "Quan", lastName: "Martin", jerseyNumber: 20, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ firstName: "Marshon", lastName: "Lattimore", jerseyNumber: 2, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },
{ firstName: "Mike", lastName: "Sainristil", jerseyNumber: 0, teamPrimaryColor: "burgundy", teamSecondaryColor: "gold" },

//Ravens
{ firstName: "DeAndre", lastName: "Hopkins", jerseyNumber: 10, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Rashod", lastName: "Bateman", jerseyNumber: 7, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Zay", lastName: "Flowers", jerseyNumber: 4, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Ronnie", lastName: "Stanley", jerseyNumber: 79, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Andrew", lastName: "Voorhees", jerseyNumber: 72, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Tyler", lastName: "Linderbaum", jerseyNumber: 64, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Daniel", lastName: "Faalele", jerseyNumber: 77, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Roger", lastName: "Rosengarten", jerseyNumber: 70, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Mark", lastName: "Andrews", jerseyNumber: 89, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Lamar", lastName: "Jackson", jerseyNumber: 8, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Derrick", lastName: "Henry", jerseyNumber: 22, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Patrick", lastName: "Ricard", jerseyNumber: 42, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Broderick", lastName: "Washington", jerseyNumber: 96, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Travis", lastName: "Jones", jerseyNumber: 98, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Justin", lastName: "Madubuike", jerseyNumber: 92, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Odafe", lastName: "Oweh", jerseyNumber: 99, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Trenton", lastName: "Simpson", jerseyNumber: 32, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Roquan", lastName: "Smith", jerseyNumber: 0, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Kyle", lastName: "Van Noy", jerseyNumber: 53, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Nate", lastName: "Wiggins", jerseyNumber: 2, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Kyle", lastName: "Hamilton", jerseyNumber: 14, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "T.J.", lastName: "Starks", jerseyNumber: 24, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Jaire", lastName: "Alexander", jerseyNumber: 23, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },
{ firstName: "Marlon", lastName: "Humphrey", jerseyNumber: 44, teamPrimaryColor: "purple", teamSecondaryColor: "gold" },

  // Bengals
{ firstName: "Ja'Marr", lastName: "Chase", jerseyNumber: 1, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
{ firstName: "Tee", lastName: "Higgins", jerseyNumber: 5, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
{ firstName: "Andrei", lastName: "Iosivas", jerseyNumber: 80, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
{ firstName: "Orlando", lastName: "Brown Jr.", jerseyNumber: 75, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
{ firstName: "Cody", lastName: "Fairchild", jerseyNumber: 63, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
{ firstName: "Ted", lastName: "Karras", jerseyNumber: 64, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
{ firstName: "Matt", lastName: "Patrick", jerseyNumber: 62, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
{ firstName: "Amarius", lastName: "Mims", jerseyNumber: 71, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
{ firstName: "Mike", lastName: "Gesicki", jerseyNumber: 88, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
{ firstName: "Joe", lastName: "Burrow", jerseyNumber: 9, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
{ firstName: "Chase", lastName: "Brown", jerseyNumber: 30, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
{ firstName: "Joseph", lastName: "Ossai", jerseyNumber: 58, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
{ firstName: "Jowon", lastName: "Slaton Jr.", jerseyNumber: 98, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
{ firstName: "Zachary", lastName: "Hill", jerseyNumber: 92, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
{ firstName: "Trey", lastName: "Hendrickson", jerseyNumber: 91, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
{ firstName: "Daijahn", lastName: "Knight Jr.", jerseyNumber: 44, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
{ firstName: "Logan", lastName: "Wilson", jerseyNumber: 55, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
{ firstName: "DJ", lastName: "Turner II", jerseyNumber: 20, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
{ firstName: "Jordan", lastName: "Battle", jerseyNumber: 27, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
{ firstName: "Tycen", lastName: "Stone", jerseyNumber: 31, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
{ firstName: "Cam", lastName: "Taylor-Britt", jerseyNumber: 29, teamPrimaryColor: "orange", teamSecondaryColor: "black" },
{ firstName: "Dax", lastName: "Hill", jerseyNumber: 23, teamPrimaryColor: "orange", teamSecondaryColor: "black" },

  // Browns
{ firstName: "Cedric", lastName: "Tillman", jerseyNumber: 19, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
{ firstName: "Jerry", lastName: "Jeudy", jerseyNumber: 3, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
{ firstName: "Jamari", lastName: "Thrash", jerseyNumber: 80, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
{ firstName: "Dawand", lastName: "Jones", jerseyNumber: 79, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
{ firstName: "Joel", lastName: "Bitonio", jerseyNumber: 75, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
{ firstName: "Ethan", lastName: "Pocic", jerseyNumber: 55, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
{ firstName: "Wyatt", lastName: "Teller", jerseyNumber: 77, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
{ firstName: "Jack", lastName: "Conklin", jerseyNumber: 78, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
{ firstName: "David", lastName: "Njoku", jerseyNumber: 85, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
{ firstName: "Joe", lastName: "Flacco", jerseyNumber: 15, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
{ firstName: "Jerome", lastName: "Ford", jerseyNumber: 34, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
{ firstName: "Alex", lastName: "Wright", jerseyNumber: 91, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
{ firstName: "Jordan", lastName: "Collins", jerseyNumber: 96, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
{ firstName: "Maurice", lastName: "Graham", jerseyNumber: 94, teamPrimaryColor: "brown", teamSecondaryColor: "pink" }, // Unusual color
{ firstName: "Myles", lastName: "Garrett", jerseyNumber: 95, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
{ firstName: "Devin", lastName: "Bush", jerseyNumber: 30, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
{ firstName: "Charlie", lastName: "Schwesinger", jerseyNumber: 49, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
{ firstName: "Denzel", lastName: "Ward", jerseyNumber: 21, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
{ firstName: "Grant", lastName: "Delpit", jerseyNumber: 9, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
{ firstName: "Ronnie", lastName: "Hickman", jerseyNumber: 33, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
{ firstName: "Greg", lastName: "Newsome II", jerseyNumber: 0, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },
{ firstName: "Mohamed", lastName: "Mitchell", jerseyNumber: 29, teamPrimaryColor: "brown", teamSecondaryColor: "orange" },

  // Steelers
{ firstName: "DK", lastName: "Metcalf", jerseyNumber: 4, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "Robert", lastName: "Woods", jerseyNumber: 16, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "Calvin", lastName: "Austin III", jerseyNumber: 19, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "Broderick", lastName: "Jones", jerseyNumber: 77, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "Isaac", lastName: "Seumalo", jerseyNumber: 73, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "Mason", lastName: "Frazier", jerseyNumber: 54, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "Spencer", lastName: "McCormick", jerseyNumber: 66, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "Troy", lastName: "Fautanu", jerseyNumber: 76, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "Pat", lastName: "Freiermuth", jerseyNumber: 88, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "Jordan", lastName: "Rodgers", jerseyNumber: 8, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "Jaylen", lastName: "Warren", jerseyNumber: 30, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "Payton", lastName: "Thomas-Jones", jerseyNumber: 48, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "Ronnie", lastName: "Harmon", jerseyNumber: 99, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "Keeanu", lastName: "Benton", jerseyNumber: 95, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "Cameron", lastName: "Heyward", jerseyNumber: 97, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "T.J.", lastName: "Watt", jerseyNumber: 90, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "Patrick", lastName: "Queen", jerseyNumber: 6, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "Trenton", lastName: "Wilson", jerseyNumber: 41, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "Alex", lastName: "Highsmith", jerseyNumber: 56, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "Darius", lastName: "Slay", jerseyNumber: 23, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "DeShon", lastName: "Elliott", jerseyNumber: 25, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "Juan", lastName: "Thornhill", jerseyNumber: 22, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "Joey", lastName: "Porter Jr.", jerseyNumber: 24, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },
{ firstName: "Jalen", lastName: "Ramsey", jerseyNumber: 5, teamPrimaryColor: "black", teamSecondaryColor: "yellow" },


  //Bears
{ firstName: "Rome", lastName: "Odunze", jerseyNumber: 15, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
{ firstName: "D.J.", lastName: "Moore", jerseyNumber: 2, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
{ firstName: "Olamide", lastName: "Zaccheaus", jerseyNumber: 14, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
{ firstName: "Braxton", lastName: "Jones", jerseyNumber: 70, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
{ firstName: "Joe", lastName: "Thuney", jerseyNumber: 62, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
{ firstName: "Drew", lastName: "Dalman", jerseyNumber: 52, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
{ firstName: "Tyreke", lastName: "Jackson", jerseyNumber: 73, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
{ firstName: "Darnell", lastName: "Wright", jerseyNumber: 58, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
{ firstName: "Colston", lastName: "Loveland", jerseyNumber: 84, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
{ firstName: "Caleb", lastName: "Williams", jerseyNumber: 18, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
{ firstName: "D'Andre", lastName: "Swift", jerseyNumber: 4, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
{ firstName: "Montez", lastName: "Sweat", jerseyNumber: 98, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
{ firstName: "Gervon", lastName: "Dexter Sr.", jerseyNumber: 99, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
{ firstName: "Grady", lastName: "Jarrett", jerseyNumber: 50, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
{ firstName: "Dayo", lastName: "Odeyingbo", jerseyNumber: 55, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
{ firstName: "T.J.", lastName: "Edwards", jerseyNumber: 53, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
{ firstName: "Tremaine", lastName: "Edmunds", jerseyNumber: 49, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
{ firstName: "Tyrique", lastName: "Stevenson", jerseyNumber: 29, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
{ firstName: "Jaquan", lastName: "Brisker", jerseyNumber: 9, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
{ firstName: "Kevin", lastName: "Byard III", jerseyNumber: 31, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
{ firstName: "Jaylon", lastName: "Johnson", jerseyNumber: 1, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },
{ firstName: "Kyler", lastName: "Gordon", jerseyNumber: 6, teamPrimaryColor: "navy", teamSecondaryColor: "orange" },

  //Lions
{ firstName: "Donovan", lastName: "Patrick", jerseyNumber: 12, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "Jameson", lastName: "Williams", jerseyNumber: 1, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "Amon-Ra", lastName: "St. Brown", jerseyNumber: 14, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "Taylor", lastName: "Decker", jerseyNumber: 68, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "Christian", lastName: "Mahogany", jerseyNumber: 73, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "Graham", lastName: "Glasgow", jerseyNumber: 60, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "Tate", lastName: "Ratledge", jerseyNumber: 69, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "Penei", lastName: "Sewell", jerseyNumber: 58, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "Sam", lastName: "LaPorta", jerseyNumber: 87, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "Jared", lastName: "Goff", jerseyNumber: 16, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "Jahmyr", lastName: "Gibbs", jerseyNumber: 0, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "Aidan", lastName: "Hutchinson", jerseyNumber: 97, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "D.J.", lastName: "Reader", jerseyNumber: 98, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "Alim", lastName: "McNeill", jerseyNumber: 54, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "Marcus", lastName: "Davenport", jerseyNumber: 92, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "Alex", lastName: "Anzalone", jerseyNumber: 34, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "Jack", lastName: "Campbell", jerseyNumber: 46, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "Derrick", lastName: "Barnes", jerseyNumber: 55, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "Terrion", lastName: "Arnold", jerseyNumber: 6, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "Brian", lastName: "Branch", jerseyNumber: 32, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "Kerby", lastName: "Joseph", jerseyNumber: 31, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "Steven", lastName: "Reed", jerseyNumber: 4, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },
{ firstName: "Amik", lastName: "Robertson", jerseyNumber: 21, teamPrimaryColor: "blue", teamSecondaryColor: "silver" },

//Packers
{ firstName: "Romeo", lastName: "Doubs", jerseyNumber: 87, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
{ firstName: "Matthew", lastName: "Golden", jerseyNumber: 22, teamPrimaryColor: "green", teamSecondaryColor: "yellow" }, 
{ firstName: "Jayden", lastName: "Reed", jerseyNumber: 11, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
{ firstName: "Josh", lastName: "Myers", jerseyNumber: 63, teamPrimaryColor: "green", teamSecondaryColor: "yellow" }, 
{ firstName: "Sean", lastName: "Rhyan", jerseyNumber: 65, teamPrimaryColor: "green", teamSecondaryColor: "yellow" }, 
{ firstName: "Elgton", lastName: "Jenkins", jerseyNumber: 74, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
{ firstName: "Zach", lastName: "Tom", jerseyNumber: 75, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
{ firstName: "Tucker", lastName: "Kraft", jerseyNumber: 85, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
{ firstName: "Jordan", lastName: "Love", jerseyNumber: 10, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
{ firstName: "Josh", lastName: "Jacobs", jerseyNumber: 8, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
{ firstName: "Rashan", lastName: "Gary", jerseyNumber: 52, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
{ firstName: "Kenny", lastName: "Clark", jerseyNumber: 97, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
{ firstName: "Devonte", lastName: "Wyatt", jerseyNumber: 95, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
{ firstName: "Lukas", lastName: "Van Ness", jerseyNumber: 90, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
{ firstName: "Quay", lastName: "Walker", jerseyNumber: 7, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
{ firstName: "Cooper", lastName: "Eddrien", jerseyNumber: 56, teamPrimaryColor: "green", teamSecondaryColor: "yellow" }, 
{ firstName: "Keisean", lastName: "Nixon", jerseyNumber: 21, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
{ firstName: "Xavier", lastName: "McKinney", jerseyNumber: 29, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
{ firstName: "Carrington", lastName: "Valentine", jerseyNumber: 33, teamPrimaryColor: "green", teamSecondaryColor: "yellow" }, 
{ firstName: "Corey", lastName: "Ballentine", jerseyNumber: 25, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },
{ firstName: "Javon", lastName: "Bullard", jerseyNumber: 20, teamPrimaryColor: "green", teamSecondaryColor: "yellow" },

  //Vikings
 { firstName: "Justin", lastName: "Jefferson", jerseyNumber: 18, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
{ firstName: "Jordan", lastName: "Addison", jerseyNumber: 3, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
{ firstName: "Jalen", lastName: "Nailor", jerseyNumber: 1, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
{ firstName: "Christian", lastName: "Darrisaw", jerseyNumber: 71, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
{ firstName: "Blake", lastName: "Brandel", jerseyNumber: 74, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" }, 
{ firstName: "Ezra", lastName: "Cleveland", jerseyNumber: 78, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
{ firstName: "Wes", lastName: "Schweitzer", jerseyNumber: 76, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" }, 
{ firstName: "Brian", lastName: "O'Neill", jerseyNumber: 75, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
{ firstName: "T.J.", lastName: "Hockenson", jerseyNumber: 87, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
{ firstName: "J.J.", lastName: "McCarthy", jerseyNumber: 9, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
{ firstName: "Aaron", lastName: "Jones Sr.", jerseyNumber: 33, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
{ firstName: "C.J.", lastName: "Ham", jerseyNumber: 30, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
{ firstName: "Jonathan", lastName: "Allen", jerseyNumber: 93, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
{ firstName: "Harrison", lastName: "Phillips", jerseyNumber: 97, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
{ firstName: "Javon", lastName: "Hargrave", jerseyNumber: 98, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
{ firstName: "Jonathan", lastName: "Greenard", jerseyNumber: 58, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
{ firstName: "Blake", lastName: "Cashman", jerseyNumber: 51, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
{ firstName: "Ivan", lastName: "Pace Jr.", jerseyNumber: 0, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
{ firstName: "Andrew", lastName: "Van Ginkel", jerseyNumber: 43, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
{ firstName: "Aaron", lastName: "Rodgers", jerseyNumber: 2, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
{ firstName: "Josh", lastName: "Metellus", jerseyNumber: 44, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
{ firstName: "Harrison", lastName: "Smith", jerseyNumber: 22, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
{ firstName: "Jeffrey", lastName: "Okudah", jerseyNumber: 21, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },
{ firstName: "Byron", lastName: "Murphy Jr.", jerseyNumber: 7, teamPrimaryColor: "purple", teamSecondaryColor: "yellow" },


//texans
  { firstName: "Nico", lastName: "Collins", jerseyNumber: 12, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { firstName: "Tee", lastName: "Higgins", jerseyNumber: 81, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { firstName: "Christian", lastName: "Kirk", jerseyNumber: 13, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { firstName: "Laremy", lastName: "Tunsil", jerseyNumber: 74, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { firstName: "Laken", lastName: "Tomlinson", jerseyNumber: 75, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { firstName: "Jarrett", lastName: "Patterson", jerseyNumber: 54, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { firstName: "Tytus", lastName: "Howard", jerseyNumber: 71, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { firstName: "Kenyon", lastName: "Green", jerseyNumber: 57, teamPrimaryColor: "navy", teamSecondaryColor: "red" }, // Assuming Fisher = Green
  { firstName: "Dalton", lastName: "Schultz", jerseyNumber: 86, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { firstName: "C.J.", lastName: "Stroud", jerseyNumber: 7, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { firstName: "Joe", lastName: "Mixon", jerseyNumber: 28, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { firstName: "Blake", lastName: "Cashman", jerseyNumber: 44, teamPrimaryColor: "navy", teamSecondaryColor: "red" }, // Assuming Brooks = Cashman
  { firstName: "Will", lastName: "Anderson", jerseyNumber: 51, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { firstName: "Tim", lastName: "Settle", jerseyNumber: 98, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { firstName: "Foley", lastName: "Fatukasi", jerseyNumber: 91, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { firstName: "Danielle", lastName: "Hunter", jerseyNumber: 55, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { firstName: "Christian", lastName: "Harris", jerseyNumber: 48, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { firstName: "Azeez", lastName: "Al-Shaair", jerseyNumber: 0, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { firstName: "Henry", lastName: "To'oTo'o", jerseyNumber: 39, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { firstName: "Derek", lastName: "Stingley", jerseyNumber: 24, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { firstName: "C.J.", lastName: "Gardner-Johnson", jerseyNumber: 23, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { firstName: "Caleb", lastName: "Bullock", jerseyNumber: 2, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { firstName: "Kwinton", lastName: "Lassiter", jerseyNumber: 4, teamPrimaryColor: "navy", teamSecondaryColor: "red" },
  { firstName: "Jalen", lastName: "Pitre", jerseyNumber: 5, teamPrimaryColor: "navy", teamSecondaryColor: "red" },

  //colts
  { firstName: "Michael", lastName: "Pittman Jr.", jerseyNumber: 11, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { firstName: "Alec", lastName: "Pierce", jerseyNumber: 14, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { firstName: "Josh", lastName: "Downs", jerseyNumber: 1, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { firstName: "Bernhard", lastName: "Raimann", jerseyNumber: 79, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { firstName: "Quenton", lastName: "Nelson", jerseyNumber: 56, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { firstName: "Tanor", lastName: "Bortolini", jerseyNumber: 60, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { firstName: "Blake", lastName: "Fisher", jerseyNumber: 71, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" }, // Goncalves assumed = Fisher
  { firstName: "Braden", lastName: "Smith", jerseyNumber: 72, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { firstName: "Jelani", lastName: "Woods", jerseyNumber: 84, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" }, // Assuming Warren = Woods
  { firstName: "Anthony", lastName: "Richardson Sr.", jerseyNumber: 5, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { firstName: "Jonathan", lastName: "Taylor", jerseyNumber: 28, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { firstName: "Kwity", lastName: "Paye", jerseyNumber: 51, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { firstName: "Grover", lastName: "Stewart", jerseyNumber: 90, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { firstName: "DeForest", lastName: "Buckner", jerseyNumber: 99, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { firstName: "Laiatu", lastName: "Latu", jerseyNumber: 97, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { firstName: "Cameron", lastName: "McGrone", jerseyNumber: 59, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { firstName: "Zaire", lastName: "Franklin", jerseyNumber: 44, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { firstName: "Jaylon", lastName: "Jones", jerseyNumber: 7, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" }, // Assuming Ward = Jones
  { firstName: "Nick", lastName: "Cross", jerseyNumber: 20, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { firstName: "Camryn", lastName: "Bynum", jerseyNumber: 0, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { firstName: "Emmanuel", lastName: "Walley", jerseyNumber: 27, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },
  { firstName: "Kenny", lastName: "Moore II", jerseyNumber: 23, teamPrimaryColor: "royalblue", teamSecondaryColor: "white" },

  //titans
  { firstName: "Justin", lastName: "Jefferson", jerseyNumber: 11, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { firstName: "Calvin", lastName: "Ridley", jerseyNumber: 0, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { firstName: "Tyler", lastName: "Lockett", jerseyNumber: 4, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { firstName: "Jaelyn", lastName: "Moore Jr.", jerseyNumber: 75, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { firstName: "Peter", lastName: "Skoronski", jerseyNumber: 77, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { firstName: "Lloyd", lastName: "Cushenberry III", jerseyNumber: 79, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { firstName: "Kevin", lastName: "Zeitler", jerseyNumber: 70, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { firstName: "JC", lastName: "Latham", jerseyNumber: 55, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { firstName: "Chigoziem", lastName: "Okonkwo", jerseyNumber: 85, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { firstName: "Jayden", lastName: "Daniels", jerseyNumber: 1, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" }, // Assuming Ward = Daniels
  { firstName: "Tony", lastName: "Pollard", jerseyNumber: 20, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { firstName: "Sebastian", lastName: "Joseph-Day", jerseyNumber: 69, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { firstName: "T'Vondre", lastName: "Sweat", jerseyNumber: 93, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { firstName: "Jeffery", lastName: "Simmons", jerseyNumber: 98, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { firstName: "Robert", lastName: "Jones", jerseyNumber: 45, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { firstName: "Cody", lastName: "Barton", jerseyNumber: 50, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { firstName: "Kenneth", lastName: "Williams Sr.", jerseyNumber: 52, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { firstName: "Arden", lastName: "Key", jerseyNumber: 49, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { firstName: "L'Jarius", lastName: "Sneed", jerseyNumber: 38, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { firstName: "Amani", lastName: "Hooker", jerseyNumber: 37, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { firstName: "Shaquill", lastName: "Woods", jerseyNumber: 25, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { firstName: "Jason", lastName: "Brownlee Jr.", jerseyNumber: 29, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },
  { firstName: "Roger", lastName: "McCreary", jerseyNumber: 21, teamPrimaryColor: "lightblue", teamSecondaryColor: "red" },

//jaguars
  { firstName: "Brian", lastName: "Thomas Jr.", jerseyNumber: 7, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "A.J.", lastName: "Brown", jerseyNumber: 5, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "Travis", lastName: "Hunter", jerseyNumber: 12, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "Walker", lastName: "Little", jerseyNumber: 72, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "Ezra", lastName: "Cleveland", jerseyNumber: 76, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "Robert", lastName: "Hainsey", jerseyNumber: 73, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "Patrick", lastName: "Mekari", jerseyNumber: 65, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "Anton", lastName: "Harrison", jerseyNumber: 77, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "Brenton", lastName: "Strange", jerseyNumber: 85, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "Trevor", lastName: "Lawrence", jerseyNumber: 16, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "Travis", lastName: "Etienne Jr.", jerseyNumber: 1, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "Travon", lastName: "Walker", jerseyNumber: 44, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "DaVon", lastName: "Hamilton", jerseyNumber: 52, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "Eric", lastName: "Armstead", jerseyNumber: 91, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "Jonathan", lastName: "Hines-Allen", jerseyNumber: 41, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "Foye", lastName: "Oluokun", jerseyNumber: 23, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "Devin", lastName: "Lloyd", jerseyNumber: 0, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "Yasir", lastName: "Abdullah", jerseyNumber: 56, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "Tyson", lastName: "Campbell", jerseyNumber: 3, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "Darious", lastName: "Williams", jerseyNumber: 22, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "Erick", lastName: "Murray", jerseyNumber: 29, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "Darnell", lastName: "Savage", jerseyNumber: 6, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },
  { firstName: "Antonio", lastName: "Lewis", jerseyNumber: 2, teamPrimaryColor: "teal", teamSecondaryColor: "gold" },

  //falcons
 { firstName: "Darnell", lastName: "Mooney", jerseyNumber: 1, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "Drake", lastName: "London", jerseyNumber: 5, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "Ray-Ray", lastName: "McCloud", jerseyNumber: 34, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "Jake", lastName: "Matthews", jerseyNumber: 70, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "Matthew", lastName: "Bergeron", jerseyNumber: 65, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "Ryan", lastName: "Neuzil", jerseyNumber: 64, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "Chris", lastName: "Lindstrom", jerseyNumber: 63, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "Kaleb", lastName: "McGary", jerseyNumber: 76, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "Kyle", lastName: "Pitts", jerseyNumber: 8, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "Michael", lastName: "Penix", jerseyNumber: 9, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "Bijan", lastName: "Robinson", jerseyNumber: 7, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "Ruke", lastName: "Orhorhoro", jerseyNumber: 98, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "David", lastName: "Onyemata", jerseyNumber: 90, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "Zach", lastName: "Harrison", jerseyNumber: 96, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "Clark", lastName: "Pearce", jerseyNumber: 27, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "Divine", lastName: "Deablo", jerseyNumber: 0, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "Kaden", lastName: "Elliss", jerseyNumber: 55, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "Leonard", lastName: "Floyd", jerseyNumber: 56, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "Mike", lastName: "Hughes", jerseyNumber: 21, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "Jessie", lastName: "Bates", jerseyNumber: 3, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "Kendall", lastName: "Fuller", jerseyNumber: 29, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "A.J.", lastName: "Terrell", jerseyNumber: 24, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },
  { firstName: "Dee", lastName: "Alford", jerseyNumber: 20, teamPrimaryColor: "#A71930", teamSecondaryColor: "#000000" },

  //panthers
 { firstName: "Xavier", lastName: "McMillan", jerseyNumber: 4, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "Antwane", lastName: "Leggette", jerseyNumber: 17, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "Adam", lastName: "Thielen", jerseyNumber: 19, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "Ikem", lastName: "Ekwonu", jerseyNumber: 79, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "Damien", lastName: "Lewis", jerseyNumber: 68, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "Austin", lastName: "Corbett", jerseyNumber: 63, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "Chandler", lastName: "Hunt", jerseyNumber: 50, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "Taylor", lastName: "Moton", jerseyNumber: 72, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "Tommy", lastName: "Tremble", jerseyNumber: 82, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "Bryce", lastName: "Young", jerseyNumber: 9, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "Chuba", lastName: "Hubbard", jerseyNumber: 30, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "Derrick", lastName: "Brown", jerseyNumber: 95, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "Neville", lastName: "Brown", jerseyNumber: 97, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "Tershawn", lastName: "Wharton", jerseyNumber: 92, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "Jihad", lastName: "Jones", jerseyNumber: 91, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "Tre", lastName: "Wallace", jerseyNumber: 32, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "Troy", lastName: "Rozeboom", jerseyNumber: 56, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "D.J.", lastName: "Wonnum", jerseyNumber: 98, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "Donte", lastName: "Jackson", jerseyNumber: 2, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "Tre'von", lastName: "Moehrig", jerseyNumber: 7, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "Nick", lastName: "Richardson", jerseyNumber: 36, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "Jaycee", lastName: "Horn", jerseyNumber: 8, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },
  { firstName: "Chau", lastName: "Smith-Wade", jerseyNumber: 26, teamPrimaryColor: "#0085CA", teamSecondaryColor: "#000000" },

  //saints
  { firstName: "Chris", lastName: "Olave", jerseyNumber: 12, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { firstName: "Brandin", lastName: "Cooks", jerseyNumber: 10, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { firstName: "Rashid", lastName: "Shaheed", jerseyNumber: 22, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { firstName: "Taliese", lastName: "Banks", jerseyNumber: 71, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { firstName: "Trevor", lastName: "Penning", jerseyNumber: 70, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { firstName: "Erik", lastName: "McCoy", jerseyNumber: 78, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { firstName: "Cesar", lastName: "Ruiz", jerseyNumber: 51, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { firstName: "Taliese", lastName: "Fuaga", jerseyNumber: 75, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { firstName: "Juwan", lastName: "Johnson", jerseyNumber: 83, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { firstName: "Spencer", lastName: "Rattler", jerseyNumber: 2, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { firstName: "Alvin", lastName: "Kamara", jerseyNumber: 41, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { firstName: "Jack", lastName: "Shepherd", jerseyNumber: 93, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { firstName: "Davon", lastName: "Godchaux", jerseyNumber: 92, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { firstName: "Bryan", lastName: "Bresee", jerseyNumber: 90, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { firstName: "Byron", lastName: "Young", jerseyNumber: 99, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { firstName: "Pete", lastName: "Werner", jerseyNumber: 20, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { firstName: "Demario", lastName: "Davis", jerseyNumber: 56, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { firstName: "Carl", lastName: "Granderson", jerseyNumber: 96, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { firstName: "Isaac", lastName: "Yiadom", jerseyNumber: 27, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { firstName: "Shaun", lastName: "Reid", jerseyNumber: 21, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { firstName: "Julian", lastName: "Blackmon", jerseyNumber: 28, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },
  { firstName: "Kool-Aid", lastName: "McKinstry", jerseyNumber: 4, teamPrimaryColor: "#D3BC8D", teamSecondaryColor: "#101820" },

  //bucs
   { firstName: "Mike", lastName: "Evans", jerseyNumber: 13, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "Chris", lastName: "Godwin", jerseyNumber: 14, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "Emeka", lastName: "Egbuka", jerseyNumber: 9, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "Tristan", lastName: "Wirfs", jerseyNumber: 78, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "Ben", lastName: "Bredeson", jerseyNumber: 68, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "Graham", lastName: "Barton", jerseyNumber: 62, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "Cody", lastName: "Mauch", jerseyNumber: 69, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "Luke", lastName: "Goedeke", jerseyNumber: 67, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "Cade", lastName: "Otton", jerseyNumber: 88, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "Baker", lastName: "Mayfield", jerseyNumber: 6, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "Bucky", lastName: "Irving", jerseyNumber: 7, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "Logan", lastName: "Hall", jerseyNumber: 90, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "Vita", lastName: "Vea", jerseyNumber: 50, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "Calijah", lastName: "Kancey", jerseyNumber: 94, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "Haason", lastName: "Reddick", jerseyNumber: 5, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "Lavonte", lastName: "David", jerseyNumber: 54, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "SirVocea", lastName: "Dennis", jerseyNumber: 8, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "YaYa", lastName: "Diaby", jerseyNumber: 0, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "Zyon", lastName: "McCollum", jerseyNumber: 27, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "Carlton", lastName: "Smith", jerseyNumber: 23, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "Antoine", lastName: "Winfield", jerseyNumber: 31, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "Jamel", lastName: "Dean", jerseyNumber: 35, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },
  { firstName: "Christian", lastName: "Izien", jerseyNumber: 29, teamPrimaryColor: "#D50A0A", teamSecondaryColor: "#34302B" },

  //broncos
  { firstName: "Courtland", lastName: "Sutton", jerseyNumber: 14, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "Marvin", lastName: "Mims", jerseyNumber: 19, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "Devaughn", lastName: "Vele", jerseyNumber: 17, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "Garett", lastName: "Bolles", jerseyNumber: 72, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "Ben", lastName: "Powers", jerseyNumber: 74, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "Luke", lastName: "Wattenberg", jerseyNumber: 60, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "Quinn", lastName: "Meinerz", jerseyNumber: 77, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "Mike", lastName: "McGlinchey", jerseyNumber: 69, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "Evan", lastName: "Engram", jerseyNumber: 1, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "Bo", lastName: "Nix", jerseyNumber: 10, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "Audric", lastName: "Harvey", jerseyNumber: 37, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "Zach", lastName: "Allen", jerseyNumber: 99, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "D.J.", lastName: "Jones", jerseyNumber: 93, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "John", lastName: "Franklin-Myers", jerseyNumber: 98, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "Jonathon", lastName: "Cooper", jerseyNumber: 0, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "Dre", lastName: "Greenlaw", jerseyNumber: 57, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "Alex", lastName: "Singleton", jerseyNumber: 49, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "Nik", lastName: "Bonitto", jerseyNumber: 15, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "Patrick", lastName: "Surtain", jerseyNumber: 2, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "Talanoa", lastName: "Hufanga", jerseyNumber: 9, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "Ja'Quan", lastName: "Jones", jerseyNumber: 22, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "Julius", lastName: "Moss", jerseyNumber: 21, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },
  { firstName: "Caden", lastName: "Barron", jerseyNumber: 12, teamPrimaryColor: "#002244", teamSecondaryColor: "#FB4F14" },

  //chiefs
  { firstName: "Xavier", lastName: "Worthy", jerseyNumber: 1, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { firstName: "Marquise", lastName: "Brown", jerseyNumber: 5, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { firstName: "Rashee", lastName: "Rice", jerseyNumber: 4, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { firstName: "Kingsley", lastName: "Simmons", jerseyNumber: 71, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { firstName: "Kingsley", lastName: "Suamataia", jerseyNumber: 76, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { firstName: "Creed", lastName: "Humphrey", jerseyNumber: 52, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { firstName: "Trey", lastName: "Smith", jerseyNumber: 65, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { firstName: "Jawaan", lastName: "Taylor", jerseyNumber: 74, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { firstName: "Travis", lastName: "Kelce", jerseyNumber: 87, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { firstName: "Patrick", lastName: "Mahomes", jerseyNumber: 15, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { firstName: "Isiah", lastName: "Pacheco", jerseyNumber: 10, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB612" },
  { firstName: "George", lastName: "Karlaftis", jerseyNumber: 56, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { firstName: "Chris", lastName: "Jones", jerseyNumber: 95, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { firstName: "Mike", lastName: "Pennel", jerseyNumber: 69, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { firstName: "Mike", lastName: "Danna", jerseyNumber: 51, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { firstName: "Drue", lastName: "Tranquill", jerseyNumber: 23, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { firstName: "Nick", lastName: "Bolton", jerseyNumber: 32, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { firstName: "Leo", lastName: "Chenal", jerseyNumber: 54, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { firstName: "Jaylen", lastName: "Watson", jerseyNumber: 35, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { firstName: "Joshua", lastName: "Hicks", jerseyNumber: 21, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { firstName: "Bryan", lastName: "Cook", jerseyNumber: 6, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { firstName: "Tre", lastName: "Fulton", jerseyNumber: 8, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },
  { firstName: "Trent", lastName: "McDuffie", jerseyNumber: 22, teamPrimaryColor: "#E31837", teamSecondaryColor: "#FFB81C" },

  //raiders
  { firstName: "Tyquan", lastName: "Thornton", jerseyNumber: 10, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { firstName: "Tre", lastName: "Tucker", jerseyNumber: 1, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { firstName: "Jakobi", lastName: "Meyers", jerseyNumber: 16, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { firstName: "Kolton", lastName: "Miller", jerseyNumber: 74, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { firstName: "Dylan", lastName: "Parham", jerseyNumber: 66, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { firstName: "Dalton", lastName: "Meredith", jerseyNumber: 61, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { firstName: "Jackson", lastName: "Powers-Johnson", jerseyNumber: 58, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { firstName: "Delmar", lastName: "Glaze", jerseyNumber: 71, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { firstName: "Brock", lastName: "Bowers", jerseyNumber: 89, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { firstName: "Aidan", lastName: "Smith", jerseyNumber: 7, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { firstName: "Ashton", lastName: "Jeanty", jerseyNumber: 2, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { firstName: "Maxx", lastName: "Crosby", jerseyNumber: 98, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { firstName: "Byron", lastName: "Butler", jerseyNumber: 69, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { firstName: "Isaiah", lastName: "Laulu", jerseyNumber: 96, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { firstName: "Malcolm", lastName: "Koonce", jerseyNumber: 51, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { firstName: "Germaine", lastName: "Pratt", jerseyNumber: 57, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { firstName: "Amari", lastName: "Roberts", jerseyNumber: 52, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { firstName: "Jeremy", lastName: "Chinn", jerseyNumber: 11, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { firstName: "Isaiah", lastName: "Pola-Mao", jerseyNumber: 20, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { firstName: "Joey", lastName: "Porter", jerseyNumber: 26, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { firstName: "Eric", lastName: "Stokes", jerseyNumber: 22, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },
  { firstName: "Darnay", lastName: "Holmes", jerseyNumber: 30, teamPrimaryColor: "#000000", teamSecondaryColor: "#A5ACAF" },

  //chargers
  { firstName: "Keon", lastName: "Harris", jerseyNumber: 9, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Quentin", lastName: "Johnston", jerseyNumber: 1, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Ladd", lastName: "McConkey", jerseyNumber: 15, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Rashawn", lastName: "Slater", jerseyNumber: 70, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Bradley", lastName: "Bozeman", jerseyNumber: 75, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Zion", lastName: "Johnson", jerseyNumber: 77, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Mekhi", lastName: "Becton", jerseyNumber: 73, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Joe", lastName: "Alt", jerseyNumber: 76, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Will", lastName: "Dissly", jerseyNumber: 89, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Justin", lastName: "Herbert", jerseyNumber: 10, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Kimani", lastName: "Hampton", jerseyNumber: 8, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Da'Shawn", lastName: "Hand", jerseyNumber: 91, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Teair", lastName: "Tart", jerseyNumber: 90, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Otito", lastName: "Ogbonnia", jerseyNumber: 93, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Tuli", lastName: "Tuipulotu", jerseyNumber: 45, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Denzel", lastName: "Perryman", jerseyNumber: 6, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Daiyan", lastName: "Henley", jerseyNumber: 0, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Khalil", lastName: "Mack", jerseyNumber: 52, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Asante", lastName: "Jackson", jerseyNumber: 26, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Derwin", lastName: "James", jerseyNumber: 3, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Alohi", lastName: "Gilman", jerseyNumber: 32, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Cam", lastName: "Hart", jerseyNumber: 20, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },
  { firstName: "Tiawan", lastName: "Still", jerseyNumber: 29, teamPrimaryColor: "#002A5E", teamSecondaryColor: "#0080C6" },

// Cardinals
  { firstName: "", lastName: "Campbell", jerseyNumber: 93, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "Tomlinson", jerseyNumber: 94, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "Robinson", jerseyNumber: 56, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "Browning", jerseyNumber: 5, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "Davis-Gaither", jerseyNumber: 27, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "Wilson Sr.", jerseyNumber: 2, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "Sweat", jerseyNumber: 10, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "Johnson", jerseyNumber: 0, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "Thompson", jerseyNumber: 34, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "Baker", jerseyNumber: 3, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "Melton", jerseyNumber: 16, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "Williams", jerseyNumber: 21, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "Harrison", jerseyNumber: 18, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "Wilson", jerseyNumber: 14, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "Dortch", jerseyNumber: 4, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "Johnson", jerseyNumber: 70, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "Brown", jerseyNumber: 63, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "Froholdt", jerseyNumber: 72, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "Adams", jerseyNumber: 74, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "Williams", jerseyNumber: 73, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "McBride", jerseyNumber: 85, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "Murray", jerseyNumber: 1, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },
  { firstName: "", lastName: "Conner", jerseyNumber: 6, teamPrimaryColor: "#97233F", teamSecondaryColor: "#FFFFFF" },

  // Rams
  { firstName: "", lastName: "Fiske", jerseyNumber: 55, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Ford", jerseyNumber: 95, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Turner", jerseyNumber: 91, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Young", jerseyNumber: 0, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Landman", jerseyNumber: 53, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Speights", jerseyNumber: 48, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Verse", jerseyNumber: 8, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Williams", jerseyNumber: 31, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Curl", jerseyNumber: 3, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Kinchens", jerseyNumber: 26, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Witherspoon", jerseyNumber: 4, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Lake", jerseyNumber: 37, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Adams", jerseyNumber: 17, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Nacua", jerseyNumber: 12, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Atwell", jerseyNumber: 5, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Jackson", jerseyNumber: 77, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Avila", jerseyNumber: 73, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Shelton", jerseyNumber: 65, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Dotson", jerseyNumber: 69, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Havenstein", jerseyNumber: 79, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Higbee", jerseyNumber: 89, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Stafford", jerseyNumber: 9, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },
  { firstName: "", lastName: "Williams", jerseyNumber: 23, teamPrimaryColor: "#003594", teamSecondaryColor: "#FFD100" },

  // 49ers
  { firstName: "", lastName: "Bosa", jerseyNumber: 97, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "Elliott", jerseyNumber: 92, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "Givens", jerseyNumber: 90, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "Williams", jerseyNumber: 98, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "Winters", jerseyNumber: 53, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "Warner", jerseyNumber: 54, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "Green", jerseyNumber: 0, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "Grant", jerseyNumber: 24, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "Pinnock", jerseyNumber: 25, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "Lenoir", jerseyNumber: 2, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "Stout", jerseyNumber: 20, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "Aiyuk", jerseyNumber: 11, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "Pearsall", jerseyNumber: 1, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "Jennings", jerseyNumber: 15, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "Williams", jerseyNumber: 71, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "Bartch", jerseyNumber: 78, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "Brendel", jerseyNumber: 64, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "Puni", jerseyNumber: 77, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "McKivitz", jerseyNumber: 68, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "Kittle", jerseyNumber: 85, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "Purdy", jerseyNumber: 13, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "McCaffrey", jerseyNumber: 23, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },
  { firstName: "", lastName: "Juszczyk", jerseyNumber: 44, teamPrimaryColor: "#AA0000", teamSecondaryColor: "#B3995D" },

  // Seahawks
  { firstName: "", lastName: "Williams", jerseyNumber: 99, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Murphy II", jerseyNumber: 91, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Reed", jerseyNumber: 90, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Lawrence", jerseyNumber: 0, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Knight", jerseyNumber: 48, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Jones IV", jerseyNumber: 13, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Nwosu", jerseyNumber: 7, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Jobe", jerseyNumber: 29, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Love", jerseyNumber: 20, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Bryant", jerseyNumber: 8, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Woolen", jerseyNumber: 27, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Witherspoon", jerseyNumber: 21, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Smith-Njigba", jerseyNumber: 11, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Valdes-Scantling", jerseyNumber: 1, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Kupp", jerseyNumber: 10, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Cross", jerseyNumber: 67, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Zabel", jerseyNumber: 76, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Oluwatimi", jerseyNumber: 55, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Haynes", jerseyNumber: 64, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Lucas", jerseyNumber: 72, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Barner", jerseyNumber: 88, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Darnold", jerseyNumber: 14, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Walker", jerseyNumber: 9, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" },
  { firstName: "", lastName: "Ouzts", jerseyNumber: 40, teamPrimaryColor: "#002244", teamSecondaryColor: "#69BE28" }







];