name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Sanity check OpenAI key
        env:
          OPENAI_API_KEY: ${{ secrets.VITE_SNAPCOUNT_API_KEY }}   # <-- your repo secret
        run: |
          set -euo pipefail
          curl -sS -f https://api.openai.com/v1/models \
            -H "Authorization: Bearer ${OPENAI_API_KEY}" \
            -H "Content-Type: application/json" \
          | head -c 200
          echo
          echo "OpenAI key looks usable."

      - name: Run tests
        run: npm test --if-present

      - name: Build
        run: npm run build --if-present