name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # 👇 IMPORTANT: this must match your Environment name in Settings
    environment: production   # or '.env.production' if you keep that name

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build (Vite)
        run: npm run build
        env:
          # 👇 Make it available to Vite at build time
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

      # (Optional) run tests before/after build
      - name: Run tests
        run: npm test --if-present

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4